### ISSUE TITLE
Unable to build aar using another aar file

### ISSUE THREAD

**Issue by DeepakPandiri** [kezong/fat-aar-android#1]
I have an aar file, I pasted it in libs folder and built an another aar using your plugin. It build successfully but I'm facing this below issue on the application side. 

Any idea?

java.lang.NoSuchFieldError: No static field avd_hide_password of type I in class Lcom/samplelibrary/R$drawable; or its superclasses (declaration of 'com.samplelibrary.R$drawable' appears in /data/app/demo.example.samplelibrary-UsdjnpGEsXDda3KVnopmZQ==/base.apk)

**Comment by kezong** [comment]
If you need embed a local aar which in libs folder，you need add the following code in build.gradle
```groovy
repositories {
    flatDir {
        dirs 'libs'
    }
}
```
and add the dependency in dependencies
```groovy
embed (name:'lib-aar',ext:'aar')
compileOnly (name:'lib-aar',ext:'aar')
```

**Comment by catEgg** [comment]
lib-aar2 build.gradle:
repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    compileOnly fileTree(include: '*.jar', dir: 'libs')
    api(name:'mars-xlog-release', ext:'aar')
}

lib-main build.gradle:
 embed (name:'mars-xlog-release',ext:'aar')
 compileOnly (name:'mars-xlog-release',ext:'aar')

I have an aar file in lib-aar2 project,but  it run error,Any ider?

Error:Could not find :mars-xlog-release:.
Required by:
    project :lib-main
<a href="searchInBuildFiles">Search in build.gradle files</a>
