### ISSUE TITLE
合并com.android.support:appcompat-v7资源文件冲突Error: Duplicate resources

### ISSUE THREAD

**Issue by Tobin-github** [kezong/fat-aar-android#101]
* What went wrong:
Execution failed for task ':lib-main:packageDebugResources'.
> [color/ripple_material_light] /Users/tobinlee/Downloads/fat-aar-android-master/example/lib-main/build/intermediates/exploded-aar/com.android.support/support-compat/27.1.1/debug/res/values/values.xml	[color/ripple_material_light] /Users/tobinlee/Downloads/fat-aar-android-master/example/lib-main/build/intermediates/exploded-aar/com.android.support/appcompat-v7/27.1.1/debug/res/values/values.xml: Error: Duplicate resources
  [color/secondary_text_default_material_light] /Users/tobinlee/Downloads/fat-aar-android-master/example/lib-main/build/intermediates/exploded-aar/com.android.support/support-compat/27.1.1/debug/res/values/values.xml	[color/secondary_text_default_material_light] /Users/tobinlee/Downloads/fat-aar-android-master/example/lib-main/build/intermediates/exploded-aar/com.android.support/appcompat-v7/27.1.1/debug/res/values/values.xml: Error: Duplicate resources
  [bool-port/abc_action_bar_embed_tabs] /Users/tobinlee/Downloads/fat-aar-android-master/example/lib-main/build/intermediates/exploded-aar/com.android.support/support-compat/27.1.1/debug/res/values-port/values-port.xml	[bool-port/abc_action_bar_embed_tabs] /Users/tobinlee/Downloads/fat-aar-android-master/example/lib-main/build/intermediates/exploded-aar/com.android.support/appcompat-v7/27.1.1/debug/res/values-port/values-port.xml: Error: Duplicate resources

**Comment by kezong** [comment]
参考#22
