### ISSUE TITLE
Error: Duplicate resources

### ISSUE THREAD

**Issue by JirkaKrivanek** [kezong/fat-aar-android#102]
Hello, I have an issue with using your plugin. I am aware that it is NOT your fault at all. The multiple binary AARs I am trying to merge do contain the "string/app_name". This is of course pointless for the AAR. But I am unable to force the authors of those AARs to behave properly: Any chance you allow to solve the merge conflicts somehow?

The full error is like this (one of many):

```
[string/app_name] 
    /Volumes/Gemalto/MBISDK/MBISDK/Public/MbiSdkLibrary/build/intermediates/exploded-aar/fr.coppernic.sdk.cpcutils/CpcUtilsLib/6.18.1/debug/res/values/values.xml	
[string/app_name] 
    /Volumes/Gemalto/MBISDK/MBISDK/Public/MbiSdkLibrary/build/intermediates/exploded-aar/com.gemalto.sprng/sprng/2.0.0/debug/res/values/values.xml: 
    Error: Duplicate resources
```

**Comment by kezong** [comment]
- **Res merge conflicts.** If the library res folder and embedded dependencies res have the same res Id(mostly `string/app_name`). A duplicate resources build exception will be thrown. To avoid res conflicts:
  - consider using a prefix to each res Id, both in library res and aar dependencies if possible. 
  - Adding "android.disableResourceValidation=true" to "gradle.properties" can do a trick to skip the exception, but is not recommended.

**Comment by JirkaKrivanek** [comment]
As I wrote, I can hardly impact those dependencies. Of course, for our dependencies, your advice is valid.

But the "android.disableResourceValidation=true" did the trick for me, so I can at least continue investigating whether your merger works for me or not...

Thank You, closing this ticket now...

**Comment by louiewh** [comment]
I also have this issure.
So any other good way to reslove ?

**Comment by daddycoding** [comment]
我也有同样的问题。提示
Duplicate resources
是2个aar 包里面so文件相同了 这个能不能加给配置 类似
 packagingOptions {
        pickFirst 'lib/*/libc++_shared.so'
    }
因为我清楚知道这2个so 文件是一致的 或者后面如果能够md5比对如果相同则保留一个

**Comment by cm1996** [comment]
> 

请问解决了么，我这也是 so 库冲突，只希望无脑选一个就 OK 了

**Comment by cm1996** [comment]
> 我也有同样的问题。提示 Duplicate resources 是2个aar 包里面so文件相同了 这个能不能加给配置 类似 packagingOptions { pickFirst 'lib/*/libc++_shared.so' } 因为我清楚知道这2个so 文件是一致的 或者后面如果能够md5比对如果相同则保留一个

请问解决了么，我这也是 so 库冲突，只希望随便选一个就行

**Comment by ACMNexus** [comment]
How to solve the asset sample resource file.

**Comment by woshiluoyong** [comment]
我遇到的问题更是诡异，提示冲突是两个路径一模一样的文件，AI分析了好久都没搞定，而且我确认就只引用了一个，没有重复引用
`stephenEmbed (name: 'sevenzipjbinding_16.02-2.02_2025_0704_1436', ext: 'aar')`

报错如下：
`AGPBI: {"kind":"error","text":"Duplicate resources","sources":[{"file":{"description":"armeabi-v7a/lib7-Zip-JBinding.so","path":"/Users/stephen/Documents/AndroidProjects/QYAndroidAccSdk/libraryAccSdk/build/intermediates/exploded-aar/sevenzipjbinding_16.02-2.02_2025_0704_1436/stephen/jni/armeabi-v7a/lib7-Zip-JBinding.so"}},{"file":{"description":"armeabi-v7a/lib7-Zip-JBinding.so","path":"/Users/stephen/Documents/AndroidProjects/QYAndroidAccSdk/libraryAccSdk/build/intermediates/exploded-aar/sevenzipjbinding_16.02-2.02_2025_0704_1436/stephen/jni/armeabi-v7a/lib7-Zip-JBinding.so"}}],"tool":"Resource and asset merger"}
AGPBI: {"kind":"error","text":"Duplicate resources","sources":[{"file":{"description":"x86/lib7-Zip-JBinding.so","path":"/Users/stephen/Documents/AndroidProjects/QYAndroidAccSdk/libraryAccSdk/build/intermediates/exploded-aar/sevenzipjbinding_16.02-2.02_2025_0704_1436/stephen/jni/x86/lib7-Zip-JBinding.so"}},{"file":{"description":"x86/lib7-Zip-JBinding.so","path":"/Users/stephen/Documents/AndroidProjects/QYAndroidAccSdk/libraryAccSdk/build/intermediates/exploded-aar/sevenzipjbinding_16.02-2.02_2025_0704_1436/stephen/jni/x86/lib7-Zip-JBinding.so"}}],"tool":"Resource and asset merger"}
AGPBI: {"kind":"error","text":"Duplicate resources","sources":[{"file":{"description":"arm64-v8a/lib7-Zip-JBinding.so","path":"/Users/stephen/Documents/AndroidProjects/QYAndroidAccSdk/libraryAccSdk/build/intermediates/exploded-aar/sevenzipjbinding_16.02-2.02_2025_0704_1436/stephen/jni/arm64-v8a/lib7-Zip-JBinding.so"}},{"file":{"description":"arm64-v8a/lib7-Zip-JBinding.so","path":"/Users/stephen/Documents/AndroidProjects/QYAndroidAccSdk/libraryAccSdk/build/intermediates/exploded-aar/sevenzipjbinding_16.02-2.02_2025_0704_1436/stephen/jni/arm64-v8a/lib7-Zip-JBinding.so"}}],"tool":"Resource and asset merger"}
AGPBI: {"kind":"error","text":"Duplicate resources","sources":[{"file":{"description":"x86_64/lib7-Zip-JBinding.so","path":"/Users/stephen/Documents/AndroidProjects/QYAndroidAccSdk/libraryAccSdk/build/intermediates/exploded-aar/sevenzipjbinding_16.02-2.02_2025_0704_1436/stephen/jni/x86_64/lib7-Zip-JBinding.so"}},{"file":{"description":"x86_64/lib7-Zip-JBinding.so","path":"/Users/stephen/Documents/AndroidProjects/QYAndroidAccSdk/libraryAccSdk/build/intermediates/exploded-aar/sevenzipjbinding_16.02-2.02_2025_0704_1436/stephen/jni/x86_64/lib7-Zip-JBinding.so"}}],"tool":"Resource and asset merger"}`

最后还是机缘巧合验证到一个现象,当我把library的buildType设置为两个单词，就是包含驼峰的（比如xxxxM）编译就不会报这个冲突，如果取一个单词(比如stephen)就会冲突，很奇怪，😅，最后喊claude结合fat-aar源码分析还是没有收获，但是感觉肯定就是Agp和fat-aar之间兼容的名字问题，所以先取两个单词规避吧！希望帮到有缘人
