### ISSUE TITLE
Merge error on R class

### ISSUE THREAD

**Issue by JirkaKrivanek** [kezong/fat-aar-android#103]
Hello again, another issue when merging:

```
/Volumes/Gemalto/MBISDK/MBISDK/Public/MbiSdkLibrary/build/intermediates/fat-R/r/debug/com/gemalto/mbi/fpscanner/coppernic/R.java:19: error: cannot find symbol
    public static final int DialogSpotColor = com.gemalto.mbi.R.attr.DialogSpotColor;
                                                                    ^
  symbol:   variable DialogSpotColor
  location: class attr
```

I do not understand where this comes from (in my sources (package/ID com.gemalto.mbi), I do not have any com.gemalto.mbi.R.attr.DialogSpotColor, so it cannot work) - perhaps it is auto-generated by the fat AAR merger?

**Comment by kezong** [comment]
From the above information, `R.attr.DialogSpotColor` belongs to `com.gemalto.mbi.fpscanner.coppernic`, maybe is a dependency of the module. 
You can find out which dependency contains R.attr.DialogSpotColor and it must be embeded in the main lib.

**Comment by JirkaKrivanek** [comment]
Actually, the DialogSpotColor (and many others) are inside of one of the AARs which I am trying to embed - see
[R.txt](https://github.com/kezong/fat-aar-android/files/3944953/R.txt)

I guess it comes from Android SDK (different version of the SDK than I am using for my build).

But when I build the app, it works fine (those are probably NOT used at all).

Which means Android gradle plugin is able to merge it somehow...

I can try to hack the AAR which makes these issues (replace the R.txt)...

**Comment by JirkaKrivanek** [comment]
I also do not understand at all things that I can see in the `build/intermediates` directory:

R.java
```
package com.gemalto.mbi;

public final class R {
  public static final class anim {
    public static final int abc_fade_in = com.gemalto.mbi.R.anim.abc_fade_in;
```

R.class
```
    public static final class anim {
        public static final int abc_fade_in;
        public static final int abc_fade_out;
        public static final int abc_grow_fade_in_from_bottom;
        public static final int abc_popup_enter;
        public static final int abc_popup_exit;
        public static final int abc_shrink_fade_out_from_bottom;
        public static final int abc_slide_in_bottom;
        public static final int abc_slide_in_top;
        public static final int abc_slide_out_bottom;
        public static final int abc_slide_out_top;
        public static final int abc_tooltip_enter;
        public static final int abc_tooltip_exit;

        public anim() {
        }

        static {
            abc_fade_in = abc_fade_in;
```

To me, it seems that the merger generates invalid R.java from the R.txt - but I do not understand what is going on behind scenes...

**Comment by JirkaKrivanek** [comment]
I abandoned this plugin as it does not do exactly what I need...

I am closing this ticket...
