### ISSUE TITLE
Obfuscation after embedding

### ISSUE THREAD

**Issue by JirkaKrivanek** [kezong/fat-aar-android#104]
Another issue: After merging multiple AARs into the big fat one, I need to apply the obfuscation.

And to make things more complex (as usually :) ) I must use the DexGuard tool.

Unfortunately, it does not fork: The embedded classes are gone after obfuscation, even if I specify the "-keep" rules.

Question: When the embedding takes place in the build chain? Before or after obfuscation?

**Comment by JirkaKrivanek** [comment]
Ups, I can see it in the build log:
- First: Embed
- Than: Obfuscate

I still do not get why some of my dependencies are gone after obfuscation (w/o obfuscation, the dependencies are there :()...

**Comment by kezong** [comment]
Now plugin have some defects in obfuscation. You must add -keep to the proguard file of main lib to take effect. Proguard file in sub module will not take effect.

**Comment by JirkaKrivanek** [comment]
I already started to write my own gradle scripts which will do the merging for me. For me it is more effective than trying to use this plugin which unfortunately does not do exactly what I need...

I am closing this ticket...
