### ISSUE TITLE
第三方库之间资源互相冲突了怎么办？（Error: Duplicate resources）

### ISSUE THREAD

**Issue by Leu-Z** [kezong/fat-aar-android#106]
依赖的几个第三方库之间资源互相冲突了，而且我也改不了，这种情况应该怎么办？

`> Task :leumodule:packageReleaseResources FAILED
[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.zyyoona7\EasyPopup\1.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.anzaizai\EasySwipeMenuLayout\1.1.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.necer.ncalendar\ncalendar\3.3.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.razerdp\AnimatedPieView\1.1.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.classic.common\multiple-status-view\1.4\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\me.jessyan\retrofit-url-manager\1.4.0\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.shuyu\GSYVideoPlayer\5.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.CymChad\BaseRecyclerViewAdapterHelper\2.9.31\release\res\values\values.xml: Error: Duplicate resources
[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.zyyoona7\EasyPopup\1.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.anzaizai\EasySwipeMenuLayout\1.1.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.necer.ncalendar\ncalendar\3.3.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.razerdp\AnimatedPieView\1.1.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.classic.common\multiple-status-view\1.4\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\me.jessyan\retrofit-url-manager\1.4.0\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.shuyu\GSYVideoPlayer\5.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.CymChad\BaseRecyclerViewAdapterHelper\2.9.31\release\res\values\values.xml: Error: Duplicate resources
[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.zyyoona7\EasyPopup\1.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.anzaizai\EasySwipeMenuLayout\1.1.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.necer.ncalendar\ncalendar\3.3.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.razerdp\AnimatedPieView\1.1.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.classic.common\multiple-status-view\1.4\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\me.jessyan\retrofit-url-manager\1.4.0\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.shuyu\GSYVideoPlayer\5.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.CymChad\BaseRecyclerViewAdapterHelper\2.9.31\release\res\values\values.xml: Error: Duplicate resources
[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.zyyoona7\EasyPopup\1.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.anzaizai\EasySwipeMenuLayout\1.1.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.necer.ncalendar\ncalendar\3.3.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.razerdp\AnimatedPieView\1.1.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.classic.common\multiple-status-view\1.4\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\me.jessyan\retrofit-url-manager\1.4.0\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.shuyu\GSYVideoPlayer\5.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.CymChad\BaseRecyclerViewAdapterHelper\2.9.31\release\res\values\values.xml: Error: Duplicate resources
[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.zyyoona7\EasyPopup\1.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.anzaizai\EasySwipeMenuLayout\1.1.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.necer.ncalendar\ncalendar\3.3.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.razerdp\AnimatedPieView\1.1.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.classic.common\multiple-status-view\1.4\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\me.jessyan\retrofit-url-manager\1.4.0\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.shuyu\GSYVideoPlayer\5.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.CymChad\BaseRecyclerViewAdapterHelper\2.9.31\release\res\values\values.xml: Error: Duplicate resources
[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.zyyoona7\EasyPopup\1.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.anzaizai\EasySwipeMenuLayout\1.1.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.necer.ncalendar\ncalendar\3.3.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.razerdp\AnimatedPieView\1.1.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.classic.common\multiple-status-view\1.4\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\me.jessyan\retrofit-url-manager\1.4.0\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.shuyu\GSYVideoPlayer\5.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.CymChad\BaseRecyclerViewAdapterHelper\2.9.31\release\res\values\values.xml: Error: Duplicate resources
[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.zyyoona7\EasyPopup\1.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.anzaizai\EasySwipeMenuLayout\1.1.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.necer.ncalendar\ncalendar\3.3.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.razerdp\AnimatedPieView\1.1.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.classic.common\multiple-status-view\1.4\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\me.jessyan\retrofit-url-manager\1.4.0\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.shuyu\GSYVideoPlayer\5.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.CymChad\BaseRecyclerViewAdapterHelper\2.9.31\release\res\values\values.xml: Error: Duplicate resources
[attr/contentView] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.anzaizai\EasySwipeMenuLayout\1.1.2\release\res\values\values.xml	[attr/contentView] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.classic.common\multiple-status-view\1.4\release\res\values\values.xml: Error: Duplicate resources

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':leumodule:packageReleaseResources'.
> [string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.zyyoona7\EasyPopup\1.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.anzaizai\EasySwipeMenuLayout\1.1.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.necer.ncalendar\ncalendar\3.3.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.razerdp\AnimatedPieView\1.1.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.classic.common\multiple-status-view\1.4\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\me.jessyan\retrofit-url-manager\1.4.0\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.shuyu\GSYVideoPlayer\5.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.CymChad\BaseRecyclerViewAdapterHelper\2.9.31\release\res\values\values.xml: Error: Duplicate resources
  [string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.zyyoona7\EasyPopup\1.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.anzaizai\EasySwipeMenuLayout\1.1.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.necer.ncalendar\ncalendar\3.3.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.razerdp\AnimatedPieView\1.1.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.classic.common\multiple-status-view\1.4\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\me.jessyan\retrofit-url-manager\1.4.0\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.shuyu\GSYVideoPlayer\5.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.CymChad\BaseRecyclerViewAdapterHelper\2.9.31\release\res\values\values.xml: Error: Duplicate resources
  [string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.zyyoona7\EasyPopup\1.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.anzaizai\EasySwipeMenuLayout\1.1.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.necer.ncalendar\ncalendar\3.3.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.razerdp\AnimatedPieView\1.1.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.classic.common\multiple-status-view\1.4\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\me.jessyan\retrofit-url-manager\1.4.0\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.shuyu\GSYVideoPlayer\5.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.CymChad\BaseRecyclerViewAdapterHelper\2.9.31\release\res\values\values.xml: Error: Duplicate resources
  [string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.zyyoona7\EasyPopup\1.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.anzaizai\EasySwipeMenuLayout\1.1.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.necer.ncalendar\ncalendar\3.3.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.razerdp\AnimatedPieView\1.1.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.classic.common\multiple-status-view\1.4\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\me.jessyan\retrofit-url-manager\1.4.0\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.shuyu\GSYVideoPlayer\5.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.CymChad\BaseRecyclerViewAdapterHelper\2.9.31\release\res\values\values.xml: Error: Duplicate resources
  [string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.zyyoona7\EasyPopup\1.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.anzaizai\EasySwipeMenuLayout\1.1.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.necer.ncalendar\ncalendar\3.3.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.razerdp\AnimatedPieView\1.1.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.classic.common\multiple-status-view\1.4\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\me.jessyan\retrofit-url-manager\1.4.0\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.shuyu\GSYVideoPlayer\5.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.CymChad\BaseRecyclerViewAdapterHelper\2.9.31\release\res\values\values.xml: Error: Duplicate resources
  [string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.zyyoona7\EasyPopup\1.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.anzaizai\EasySwipeMenuLayout\1.1.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.necer.ncalendar\ncalendar\3.3.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.razerdp\AnimatedPieView\1.1.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.classic.common\multiple-status-view\1.4\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\me.jessyan\retrofit-url-manager\1.4.0\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.shuyu\GSYVideoPlayer\5.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.CymChad\BaseRecyclerViewAdapterHelper\2.9.31\release\res\values\values.xml: Error: Duplicate resources
  [string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.zyyoona7\EasyPopup\1.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.anzaizai\EasySwipeMenuLayout\1.1.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.necer.ncalendar\ncalendar\3.3.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.razerdp\AnimatedPieView\1.1.3\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.classic.common\multiple-status-view\1.4\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\me.jessyan\retrofit-url-manager\1.4.0\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.shuyu\GSYVideoPlayer\5.0.2\release\res\values\values.xml	[string/app_name] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.CymChad\BaseRecyclerViewAdapterHelper\2.9.31\release\res\values\values.xml: Error: Duplicate resources
  [attr/contentView] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.github.anzaizai\EasySwipeMenuLayout\1.1.2\release\res\values\values.xml	[attr/contentView] D:\Android\AndroidStudioProjects\Company\JiaoYuYun2.0\JiaoYuYun\leumodule\build\intermediates\exploded-aar\com.classic.common\multiple-status-view\1.4\release\res\values\values.xml: Error: Duplicate resources

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.`

**Comment by kezong** [comment]
* **资源冲突：** 如果library和module中含有同名的资源(比如 `string/app_name`)，编译将会报`duplication resources`的相关错误，有两种方法可以解决这个问题：
  * 考虑将library以及module中的资源都加一个前缀来避免资源冲突； 
  * 在`gradle.properties`中添加`android.disableResourceValidation=true`可以忽略资源冲突的编译错误，程序会采用第一个找到的同名资源作为实际资源，不建议这样做，如果资源同名但实际资源不一样会造成不可预期的问题。

**Comment by Leu-Z** [comment]
@kezong 
解决方法一：第三方库没法直接改资源名字，除非下载下来改。
解决方法二：不建议这样做。

**Comment by dyguests** [comment]
方法2 解决了我的问题。感谢～～！
