### ISSUE TITLE
facebook aar打包问题

### ISSUE THREAD

**Issue by kawais** [kezong/fat-aar-android#108]
子模块需要引用facebook login
implementation 'com.facebook.android:facebook-login:5.0.0'
然后主模块中加入
    embed project(path: ':sublib', configuration:'default')
    embed 'com.facebook.android:facebook-login:5.0.0'
build的时候会报错
 error: resource style/com_facebook_button (aka  mainlib:style/com_facebook_button) not found.

**Comment by kezong** [comment]
embed并不会合并com.facebppk.android:facebook-login:5.0.0的依赖项。
有两种办法
1. 第一种你可以找到pom.xml文件，找到dependency关系，将其他的库全部embed进来。
2. 在主模块的build.gradle中加上configurations.embed.transitive = true
