### ISSUE TITLE
 Could not find method embed()

### ISSUE THREAD

**Issue by xuhang1993** [kezong/fat-aar-android#109]
Could not find method embed() for arguments [DefaultProjectDependency{dependencyProject='project ':flutter_boost'', configuration='default'}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

是不是因为gradle版本太高的原因 embed方法被改成别的了

**Comment by kezong** [comment]
你用的gradle和gradle plugin什么版本。
embed是插件内定义的方法，非系统方法，可以再检查下自己工程配置。

**Comment by xuhang1993** [comment]
gradle版本是4.6 插件是3.2.1 是太低了吗

**Comment by kezong** [comment]
不会，感觉像是网络问题，插件没有加载下来。

**Comment by xuhang1993** [comment]
这是什么插件呢 我可以搜索下载吗

**Comment by myj420** [comment]
我也遇到同样的错误 怎么解决的

**Comment by pjdhanhan** [comment]
应该是配置不对
文件是按顺序执行的，
apply plugin: 'com.kezong.fat-aar'应该要放在使用embed()执行。不知道你是否也是这样的问题
