### ISSUE TITLE
Excluding embedded dependency

### ISSUE THREAD

**Issue by himgupta229** [kezong/fat-aar-android#110]
Hey,

I am using your plugin to embed one library into my library. So my use case is as below:

I am creating **library1** which internally depends on **library2** which is an aar.I push **library1**  to jcenter which my customer uses since **library2** is an aar,
I have used your plugin to embed **library2** in my **library1**.
Now the issue is one of my merchants also wants to use **library2** in its application. When he does so he is getting **_dexmerger exception for duplicate entry_**. How can I let him do the same as he can't remove that dependency **library2** from its project. Is there any way by which he can exclude **library2** from **library1**?

**Comment by nateridderman-lilly** [comment]
I have a similar issue, where a library module was included as part of several other library modules. When more than one of the other modules were included in an app, I got errors for duplicate resources.

**Comment by kezong** [comment]
compileOnly library2 in application.
