### ISSUE TITLE
有方法即将过时

### ISSUE THREAD

**Issue by CrazyLeoJay** [kezong/fat-aar-android#112]
编译器报警告：
INFO: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

这个会影响到之后的使用吗，所以是否要提前寻找这个方法的替代方案

**Comment by comann** [comment]
Maybe another duplicate. https://github.com/kezong/fat-aar-android/issues/105

**Comment by kezong** [comment]
Fixed it in 1.2.12
