### ISSUE TITLE
 API 'variantOutput.getPackageLibrary()' is obsolete

### ISSUE THREAD

**Issue by xxumbroxx** [kezong/fat-aar-android#115]
when i compiled, i had this error

INFO: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: zyfacial_v3

i use this
Android Studio 3.5.2
gradle-5.4.1-all.zip
com.android.tools.build:gradle:3.5.3

**Comment by comann** [comment]
I get this error to. I use the `-Pandroid.debug.obsoleteApi=true` flag.


[stacktrace.txt](https://github.com/kezong/fat-aar-android/files/4387454/stacktrace.txt)

**Comment by comann** [comment]
I think this is a duplicate  https://github.com/kezong/fat-aar-android/issues/105
