### ISSUE TITLE
failed to build when embed library which has flavors

### ISSUE THREAD

**Issue by kingori** [kezong/fat-aar-android#117]
I've tried to embed a library which has custom flavor dimension. But I got `Could not resolve project` error.

I've reproduced this error on example project by modifying some codes like below.

1. define flavorDimension in  `/lib-aar/build.gradle`
```
android {
  ...
  flavorDimensions "stage"

    productFlavors {
        alpha {
            dimension "stage"
        }

        production {
            dimension "stage"
        }
    }
}
```

2. define same flavorDimension in `/lib-main/build.gradle`

3. run `assembleDebug` and got error 
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':lib-main'.
> Could not resolve all dependencies for configuration ':lib-main:embed'.
   > Could not resolve project :lib-aar.
     Required by:
         project :lib-main
      > Project :lib-main declares a dependency from configuration 'embed' to configuration 'debug' which is not declared in the descriptor for project :lib-aar.
```

4. if I run `assembleAlphaDebug` , build succeed. But `lib-aar` is not built. In log, below line is printed. And as lib-aar is not included, I can't access lib-aar's code.

```
[fat-aar][unResolve dependency detected][example:lib-aar:unspecified]
```

How can I workaround this problem?

I've tested on gradle 6.0.1

**Comment by kezong** [comment]
Fixed it. 
Try to upgrade plugin to 1.3.1 or higher.
