### ISSUE TITLE
multiple module aar build not correctly

### ISSUE THREAD

**Issue by vickyleu** [kezong/fat-aar-android#12]
三个模块
first ----->
provided fileTree(include: ['*.jar'], dir: 'libs')
provided 'com.google.android.material:material:1.0.0'
provided 'androidx.legacy:legacy-support-v4:1.0.0'
//    embed (name:'alipaySdk-20180601',ext:'jar')
这里有一个支付宝的jar包,embed加不加都会往里面放
不能用compileOnly,不然AndroidX和一大堆支持包都往里面放了
provided (name:'alipaySdk-20180601',ext:'jar') 
<------first

others->>>>>>
embed "com.github.Justson:Downloader:v4.0.3"
provided 'com.github.Justson:Downloader:v4.0.3'
compileOnly 'com.google.android.material:material:1.0.0'
compileOnly 'androidx.legacy:legacy-support-v4:1.0.0'
//embed project(path: ':agentweb-core', configuration:'default')
//provided project(path: ':agentweb-core')
//embed (name:'agentweb-core',ext:'aar')
implementation (name:'agentweb-core',ext:'aar')
<<<<<<<-others

只有第一个模块不存在支持包的依赖,其它的怎么搞都有

**Comment by vickyleu** [comment]
![QQ20190617-195343](https://user-images.githubusercontent.com/19390292/59602490-70043c80-9139-11e9-8a52-a39dedf0a8ff.png)
![QQ20190617-195355](https://user-images.githubusercontent.com/19390292/59602491-70043c80-9139-11e9-9667-32f109c69aea.png)

**Comment by vickyleu** [comment]
也不知道我这个形容能不能看懂

**Comment by kezong** [comment]
没怎么看懂，embed建议是使用在一个主module中的，将需要整体打包的依赖加上embed，这样生成的aar就会包含该aar中的代码与资源。  不建议在多个module中使用。
