### ISSUE TITLE
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/

### ISSUE THREAD

**Issue by waryard** [kezong/fat-aar-android#124]
如果不打aar直接module用回报这个错

**Comment by aolmez** [comment]
Do you find any solution for this problem ?

**Comment by Farhad7d7** [comment]
i ran into this too

**Comment by waryard** [comment]
> Do you find any solution for this problem ?

I only use AAR at present , Inconvenient to use

**Comment by lqx30716** [comment]
同问，主module依赖使用了apply plugin: 'com.kezong.fat-aar'的子module，点击debug运行，子module embed的aar文件一直报java.lang.NoClassDefFoundError: Failed resolution of，如果去掉fat-aar，运行没有问题，这是什么情况呢

**Comment by liujingg** [comment]
try downgrade gradle plugin to 3.4.2, it works for me

**Comment by kezong** [comment]
该插件目前只适用于合并aar打包的场景，目前不支持用于app的直接编译。

如果需要兼容可以考虑使用参数控制，生成aar时候使用embed，直接使用时改用api接口。

**Comment by kesco** [comment]
> 该插件目前只适用于合并aar打包的场景，目前不支持用于app的直接编译。
> 
> 如果需要兼容可以考虑使用参数控制，生成aar时候使用embed，直接使用时改用api接口。

能否给个示例呢？
