### ISSUE TITLE
Not working for Build Variants version 1.2.9 for gradle 3.6.1

### ISSUE THREAD

**Issue by MichalDanielDobrzanski** [kezong/fat-aar-android#126]
`Execution failed for task ':vendorsdk:createRsFilesomevariantRelease'.
> No signature of method: com.kezong.fataar.RProcessor.IllegalAccessException() is applicable for argument types: (org.codehaus.groovy.runtime.GStringImpl) values: [{/Users/me/projects/myproject/build/intermediates/compile_symbol_list/somevariant/release/R.txt} not found]
`

Looks like new Gradle build system creates in intermediates folder:
- somevariantDebug
- somevariantRelease

folders. Hence, fat-aar cannot find **release** folder. Fat-aar should respect variant folders.

**Comment by kezong** [comment]
Fixed in 1.2.10
