### ISSUE TITLE
运行提示找不到embed的lib的R资源

### ISSUE THREAD

**Issue by berry-geng** [kezong/fat-aar-android#128]
1、lib依赖lib1，lib1 embed到lib中
embed project(path: ':lib1', configuration: 'default')
2、app 依赖lib
implementation project(':lib')
3、运行时报错，找不到lib1中R.class
![image](https://user-images.githubusercontent.com/61308643/77623368-f37d7480-6f7a-11ea-8ed8-7439a6e657e4.png)
R的包名lib1 的manifest里的包名

引用的fat-aar和gradle plugin版本号：
classpath 'com.kezong:fat-aar:1.2.9'
classpath 'com.android.tools.build:gradle:3.4.1'

**Comment by ChenKunFeng** [comment]
可能是宿主工程跟lib1的布局文件命名一样，导致加载的宿主工程的资源

**Comment by berry-geng** [comment]
> 可能是宿主工程跟lib1的布局文件命名一样，导致加载的宿主工程的资源

这是在strings.xml里的资源啊，不能同名吗。
![image](https://user-images.githubusercontent.com/61308643/77630909-c6cf5a00-6f86-11ea-9045-32b9c4a7fa7b.png)

我看资源已经打到lib里了，就是运行时找不到lib1对应的R。
比如lib1包名是com.berry.lib1，运行时报错找不到com.berry.lib1.R

**Comment by berry-geng** [comment]
@kezong 看你在问题11中这样回复了。
我了解你的意思了，现在确实没有办法解决这种问题，因为一个aar中只能包含一个R.txt，如果仅仅只是将R.txt合并是不够的，因为这样会在打包apk的时候，将所有R.txt中的资源全都生成在该aar的packageName的包名下，这样就导致原来子module中import的其实是子module包名下的R，而在最后apk中，R却变到了主aar的包名下，导致子module中R类找不到。

现在插件的做法是做了两步：

  将所有R.txt合并，这样最后生成apk时，会统一生成主module包名下的R.class文件
  根据所有子module的R.txt生成r-classes.jar，目的是做一层映射，将所有的子module包名下的R全部映射到主module的R。

现在我的lib1中资源没有映射到lib的R中，是什么原因呢，是不是哪儿没配置？

**Comment by berry-geng** [comment]
之前app是工程依赖的方式依赖lib：implementation project(':lib')
把lib编成aar，放到libs下本地依赖那个问题没了。
