### ISSUE TITLE
so文件缺失

### ISSUE THREAD

**Issue by zhanlan123** [kezong/fat-aar-android#13]
![QQ图片20190618100952](https://user-images.githubusercontent.com/7822852/59648317-3d962600-91b1-11e9-9923-cff7e47a45f9.png)
如图所示使用assembleRelease 打包

**Comment by kezong** [comment]
我一直是使用mac测试的，是没有问题的。
因为我现在没有windows的机器，所以现在暂时还无法定位原因，有时间我弄台windows看看是否会复现该问题。

**Comment by zhanlan123** [comment]
好的

**Comment by kezong** [comment]
已在`1.2.4`版本中修复该问题
