### ISSUE TITLE
将fat-aar-android用于子module，主app直接引用子module，aar丢失

### ISSUE THREAD

**Issue by wangwangchen** [kezong/fat-aar-android#130]
如题，aar无法打到apk里。如果把子module打包到maven的，主app引用maven地址，这样是没问题的。

**Comment by kezong** [comment]
该插件目前只适用于合并aar打包的场景，目前不支持用于app的直接编译。

如果需要兼容可以考虑使用参数控制，生成aar时候使用embed，直接使用时改用api接口。

**Comment by l376571926** [comment]
> 该插件目前只适用于合并aar打包的场景，目前不支持用于app的直接编译。
> 
> 如果需要兼容可以考虑使用参数控制，生成aar时候使用embed，直接使用时改用api接口。

怎么设置呢，我也是碰到这个问题了，打出的aar包可以给第三方使用，但是app模块就使用不到了，要用api才能使用
