### ISSUE TITLE
ERROR: Could not find method embed()

### ISSUE THREAD

**Issue by PiPiCaptain** [kezong/fat-aar-android#132]
以下是运行环境：

Android Studio 3.5.3
Build #AI-191.8026.42.35.6010548, built on November 15, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6

gradle-5.4.1

com.kezong:fat-aar:1.2.8

**Comment by kezong** [comment]
插件没加载成功，自己检查下看是不是哪配置有问题，可以参考demo，如果还不行可能是网络问题

**Comment by myj420** [comment]
同样的问题 请问解决了吗
