### ISSUE TITLE
R.jar as it does not exist.

### ISSUE THREAD

**Issue by MicroSummer** [kezong/fat-aar-android#133]
* What went wrong:
Execution failed for task ':yw_opensdk:compileRsDebug'.
> Cannot expand ZIP '/Users/xxx/StudioProjects/xxx/xxx/build/intermediates/compile_only_not_namespaced_r_class_jar/debug/generateDebugRFile/R.jar' as it does not exist.

**Comment by kezong** [comment]
com.android.tools.build:gradle版本多少

**Comment by MicroSummer** [comment]
现在OK了，是我这边的配置问题
