### ISSUE TITLE
Unkonw Error

### ISSUE THREAD

**Issue by Aisheng** [kezong/fat-aar-android#134]
当我这样配置的时候：
![image](https://user-images.githubusercontent.com/19602202/79213504-e0740b00-7e7b-11ea-8ebc-ac9d93d5bca5.png)
会如下的错误：
![image](https://user-images.githubusercontent.com/19602202/79213582-08636e80-7e7c-11ea-9118-694737da99f2.png)
当我去掉 configuration:'default'的配置时，又会报下面这样的错误
![image](https://user-images.githubusercontent.com/19602202/79213710-347eef80-7e7c-11ea-9b6c-85a165caca79.png)
我用的版本是：1.2.11
gradle版本：3.1.1
请问这是什么问题？谢谢。

**Comment by kezong** [comment]
./gradlew clean一下再试试
