### ISSUE TITLE
java.lang.NoSuchFieldError: No static field endpoint_amazon_init_prod of type I in class Lcom/aitime/android/payment/R$string;

### ISSUE THREAD

**Issue by AiTimeCredit** [kezong/fat-aar-android#136]
gradle版本：5.6.4
gradle plugin：3.6.2
fat-aar：1.2.11

当前版本下生成的R.txt里面的资源ID全部都是0x0，运行时报错java.lang.NoSuchFieldError: No static field：
>int anim abc_fade_in 0x0
>int anim abc_fade_out 0x0
>int string endpoint_amazon_init_local 0x0
>int string endpoint_amazon_init_prod 0x0
>int string endpoint_amazon_init_test 0x0
>int string endpoint_amazon_order_local 0x0
>int string endpoint_amazon_order_prod 0x0
>int string endpoint_amazon_order_test 0x0

gradle plugin使用3.5.3生成的aar使用起来是正常的，R.txt里面的资源ID也是正常的。

**Comment by kezong** [comment]
Try upgrade plugin to latest version
