### ISSUE TITLE
Request Relocation feature

### ISSUE THREAD

**Issue by kristiyanP** [kezong/fat-aar-android#143]
Would be nice to have a relocation option to avoid duplicate classes or conflicts.

For example this feature is available in shadowJar and works pretty well over there. 
[https://imperceptiblethoughts.com/shadow/configuration/relocation/](https://imperceptiblethoughts.com/shadow/configuration/relocation/)

It would be nice to see it also in this project.

**Comment by kezong** [comment]
It is supported in 1.3.1
