### ISSUE TITLE
Fail to generate correctly fataar when using airbnb's paris library

### ISSUE THREAD

**Issue by kristiyanP** [kezong/fat-aar-android#144]
From my understanding of [airbnb paris](https://github.com/airbnb/paris) the R.java over there is treated in a different way. 
Basically it generates a R2.class to avoid some hindrance of the android platform.

Would be nice to understand how the fat aar plugin generates the R.styles of a sub dependecy.

In the use case of this library the error which is given at runtime is the following:
```java
No static field Custom_TextView_Title of type I in class Lcom/company/sdk_design/R$style; or its superclasses (declaration of 'com.company.sdk_design.R$style' appears in /data/app/com.company.demo_android_sdk.debug-SrxhxYzDS25MrOCe12Ns-A==/base.apk)
```

I may do a PR in case you wish the plugin to handle also this use case.

Thank you

**Comment by kezong** [comment]
Try upgrade plugin to latest version.
