### ISSUE TITLE
compileOnly error

### ISSUE THREAD

**Issue by MicroSummer** [kezong/fat-aar-android#146]
implementation 'com.android.support.constraint:constraint-layout:1.1.3'
改成
compileOnly 'com.android.support.constraint:constraint-layout:1.1.3'
出错

AGPBI: {"kind":"error","text":"Android resource linking failed","sources":[{"file":"/Users//StudioProjects/XXX/qrbusiness/pluginmodule_api/build/intermediates/packaged_res/release/layout/qr_card_layout_expand_all.xml","position":{"startLine":7}}],"original":"/Users/xxx/StudioProjects/XXX/qrbusiness/pluginmodule_api/build/intermediates/packaged_res/release/layout/qr_card_layout_expand_all.xml:8: AAPT: error: attribute layout_constraintBottom_toBottomOf (aka com.xxx.xxx.basic:layout_constraintBottom_toBottomOf) not found.\n    ","tool":"AAPT"}

**Comment by zhaowenliang** [comment]
+1
