### ISSUE TITLE
Jars do not included when using flavors

### ISSUE THREAD

**Issue by nillsondg** [kezong/fat-aar-android#154]
Jar variants don't included into result arr when using any flavor configuration in library project.
Tested on version of plugin: 1.2.12-15.
You can also reproduce this issue in example project:
For flavor1 and flavor2 result arr included only: 
—libaar, 
—libaar2, 
—libaarlocal, 
—libaar2, 
—libaarlocal2
This issue also affects transient dependencies.

**Comment by nillsondg** [comment]
I found out that first version affected by issue 1.2.10. Arrs builded by 1.2.9 include jars

**Comment by kezong** [comment]
Fixed in 1.2.17
