### ISSUE TITLE
上传aar maven报错

### ISSUE THREAD

**Issue by duanhaolxc** [kezong/fat-aar-android#16]
A problem was found with the configuration of task ':login:mergeReleaseManifest'.
pecified for property 'mainManifestFile' does not exist.

**Comment by kezong** [comment]
出现这种问题，往往是gradle plugin版本问题。
有可能在com.android.tools.build:gradle中虽然声明的是3.3.0，但是实际上有某一个module又依赖了3.1.0的gradle plugin。

解决该问题的办法是统一gradle plugin的版本。
