### ISSUE TITLE
error merge manifest when use transitive = true

### ISSUE THREAD

**Issue by siavash-sajjad** [kezong/fat-aar-android#162]
hi
i get manifest merged or below error when user transitive = true.

Type android.support.v4.app.INotificationSideChannel is defined multiple times: D:\Project\Android\packagename2\sdk_notif\build\.transforms\7c4441187f527206eff062ca9bf8877d\classes\classes.dex, D:\Project\Android\packagename2\app\build\intermediates\external_libs_dex\debug\mergeExtDexDebug\classes.dex

`apply plugin: 'com.android.library'
apply plugin: 'com.kezong.fat-aar'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    ndkVersion '21.0.6113669'
    externalNativeBuild {
        cmake {
            path 'src/main/jni/CMakeLists.txt'
        }
    }
}
configurations.embed.transitive = true
dependencies {
    embed "com.squareup.okhttp3:okhttp:4.7.2"
    embed  'com.github.bumptech.glide:glide:4.11.0'
    embed  'com.github.bumptech.glide:compiler:4.11.0'
    embed  'com.google.firebase:firebase-messaging:20.2.1'
}
`

**Comment by kezong** [comment]
multi module contains support.v4 libs.
you need exclude it.
