### ISSUE TITLE
使用ArtiFactory时，configurations.compile.resolvedConfiguration.firstLevelModuleDependencies为空

### ISSUE THREAD

**Issue by qqnp1100** [kezong/fat-aar-android#165]
想将远程依赖写在pom中，但是`configurations.compile.resolvedConfiguration.firstLevelModuleDependencies`为空，读不到依赖

以前是用android-fat-aar，这样写是可以读到远程依赖
`
List<String> embedList = new ArrayList<>();
            Map<String, ResolvedDependency> depList = new LinkedHashMap<>();

            //List all embedded dependencies
            configurations.embed.allDependencies.each {
                def depName = String.format("%s:%s", it.group, it.name)
                embedList.add(depName);
            }

            //Collect all first level dependencies except embedded ones
            configurations.compile.resolvedConfiguration.firstLevelModuleDependencies.each {
                ResolvedDependency dep ->
                    def depName = String.format("%s:%s", dep.moduleGroup, dep.moduleName)
                    if (!embedList.contains(depName) && !depList.containsKey(depName)) {
                        depList.put(depName, dep)
                    }
            }

            //Collect all second level dependencies of embedded ones
            configurations.embed.resolvedConfiguration.firstLevelModuleDependencies.each {
                //Second Level Depenencies
                it.children.each {
                    ResolvedDependency dep ->
                        def depName = String.format("%s:%s", dep.moduleGroup, dep.moduleName)
                        if (!embedList.contains(depName) && !depList.containsKey(depName)) {
                            depList.put(depName, dep)

                        }
                }
            }
`

**Comment by kezong** [comment]
建议了解一下代码的原理，不要直接复制，在另一个插件中能使用，不一定适用于该插件。

如果要添加依赖进pom文件，直接implementation该远程仓库就行，不需要再写复杂的脚本。
