### ISSUE TITLE
关于 AppCompat-v7 打包出现资源冲突的问题

### ISSUE THREAD

**Issue by zyowo** [kezong/fat-aar-android#166]
感谢您提供这么好的工具！
想问一下，我在制作一个 Unity 的 aar 插件，因为 Unity 导出时是不带 AppCompat 的，而我使用的 uvc 库是使用了
```
	implementation "com.android.support:support-v4:${supportLibVersion}"
	implementation "com.android.support:appcompat-v7:${supportLibVersion}"
	implementation "com.android.support:recyclerview-v7:${supportLibVersion}"
	implementation "com.android.support:preference-v7:${supportLibVersion}"
```

当我 embed 这个 uvc 库时，就提示 资源冲突的问题。
如果只考虑使用一个 aar 文件，最好的选择就是 `android.disableResourceValidation=true` 来取消资源冲突的报错？
感谢解答。

**Comment by zyowo** [comment]
#22

**Comment by kezong** [comment]
Trying to upgrade to the latest version should fix the problem.
