### ISSUE TITLE
你好请教一下关于生成的aar包里有部分类找不到，报错NoClassDefFoundError

### ISSUE THREAD

**Issue by ijoncc** [kezong/fat-aar-android#168]
感谢作者的开源项目！
我发现在mainLib依赖aar1和aar2，aar1包里的classes.jar代码混淆过，aar2没做混淆，然后生成最终的aar包里，找不到aar1里的部分类，报错NoClassDefFoundError，我把作者的example下载到本地，将aar1和aar2两个包放到example里的lib-main下，编译最后出来的aar包里也是会找不到aar1里的部分类，请问您的项目对混淆过的aar包有处理吗？

**Comment by AiYouWei** [comment]
我也遇到了这个问题 kotlin代码的好多方法 无法引用

**Comment by a64307410** [comment]
我也一样，2个都混淆，出现NoClassDefFoundError，不合并则正常。然后不混淆合并正常，why

**Comment by sunqihui222** [comment]
我也遇到了

**Comment by kezong** [comment]
混淆打包aar，proguard会过滤掉没有被调用的类，如果要保留，需要加在proguard.txt中加keep
