### ISSUE TITLE
NoSuchFieldError: No static field of type I in class

### ISSUE THREAD

**Issue by Kamil-H** [kezong/fat-aar-android#170]
Hi,
First of all I would like to thank you for your work on plugin, it's great and allows us build libraries from multi-module projects. 

I would like to describe an issue I'm facing. I'm using the plugin to build following library:
https://bintray.com/audioburst/maven/audioburst_player
When I'm testing the solution in the demo app available here:
https://github.com/audioburst-labs/AudioburstPlayer-Android
it is working great. I'm not encountering any crashes or problems related to building process.
However when I'm trying to integrate it in another Android project I'm constantly getting following crash:
`Caused by: java.lang.NoSuchFieldError: No static field navigationButton of type I in class Lcom/audioburst/audioburst_player/R$id; or its superclasses (declaration of 'com.audioburst.audioburst_player.R$id' appears in /data/app/com.kamilh.gotcharacters-BY8ie52eN3y5V_pmKKxdkA==/base.apk)`
Here is the sample problem that is affected by the problem:
https://github.com/Kamil-H/GoTCharacters/tree/audioburst_player

It seems like under some condition the `R` file that is included in the library is for some reason wrong
In build process I'm using Proguard, however I also tried to disable it and the result was the same - crash still appears. 
I also tried to change name of the `navigationButton` property and it didn't help. 

Is there anything I can check/do to try to fix this problem?

Thank you in advance.

**Comment by CreatedFromZhang** [comment]
There are similar situations，combine resources and general R class have some problem. lost some resource on build project , advise use other lib  to fix this problem

**Comment by Kamil-H** [comment]
What are the other libs you are referring to?

**Comment by kezong** [comment]
Trying to upgrade the plugin to the latest version should fix the problem
