### ISSUE TITLE
Doesn't work with *.kts files

### ISSUE THREAD

**Issue by lukaszkalnik** [kezong/fat-aar-android#175]
We have our project configured in `build.gradle.kts` files, including the top-level file.

In top level `build.gradle.kts` I set:
```
buildscript {
    repositories {
        jcenter()
        maven("https://plugins.gradle.org/m2/")  
    }
    dependencies {
        classpath(kotlin("gradle-plugin", Dependencies.Version.kotlinVersion))
        classpath(group = "com.kezong", name = "fat-aar", version = "1.2.15")
    }
}
```

Then in the library project I set:
```
plugins {
    id("com.android.library")
    id("com.kezong.fat-aar")
}
```

However then I get the following error:
```
Cause: com.android.tools.build:gradle is no set in the root build.gradle file
```
The error disappears as soon as I remove the following line from the top-level `build.gradle.kts` file:
```
// classpath(group = "com.kezong", name = "fat-aar", version = "1.2.15")
```
but then the project obviously cannot find the fat-aar plugin.

Android Gradle plugin version: 4.0.0
Gradle version: 6.4

**Comment by kezong** [comment]
Fixed it in 1.3.1
