### ISSUE TITLE
能否支持pom发布maven合并

### ISSUE THREAD

**Issue by lianyagang** [kezong/fat-aar-android#179]
场景A 依赖B B implemention远程，但是合并aar后不想把implementation打入包中，最终发布maven的时候，把B的远程依赖打入pom文件

**Comment by lianyagang** [comment]
突然发现这个开源，设计的很好。但是在我各种在实际业务中尝试之后，得出的一个小小的结论。
合并aar，最好仅限于自己业务上面的合并，如果涉及到第三方，还是不要尝试了。太多资源冲突的问题了。解决这些问题，应该不是这个库的设计初衷。例如，我们所知道的，Flutter资源合并，以及RN的资源合并等。我觉得这个库都不适用

**Comment by kezong** [comment]
> 场景A 依赖B B implemention远程，但是合并aar后不想把implementation打入包中，最终发布maven的时候，把B的远程依赖打入pom文件

暂不支持，建议将远程仓库在A中implemention。
