### ISSUE TITLE
Error: Duplicate resources for task module:packageReleaseAssets'.

### ISSUE THREAD

**Issue by edwnmrtnz** [kezong/fat-aar-android#183]

**Comment by pikacode** [comment]
+1

**Comment by wolongalick** [comment]
Execution failed for task ':ModuleC:packageReleaseResources'.
> [attr/closeIcon] D:\studio_workspace\SiHuo\FatAarApp\ModuleC\build\intermediates\exploded-aar\com.google.android.material\material\1.2.1\release\res\values\values.xml	[attr/closeIcon] D:\studio_workspace\SiHuo\FatAarApp\ModuleC\build\intermediates\exploded-aar\androidx.appcompat\appcompat\1.2.0\release\res\values\values.xml: Error: Duplicate resources
  [attr/icon] D:\studio_workspace\SiHuo\FatAarApp\ModuleC\build\intermediates\exploded-aar\com.google.android.material\material\1.2.1\release\res\values\values.xml	[attr/icon] D:\studio_workspace\SiHuo\FatAarApp\ModuleC\build\intermediates\exploded-aar\androidx.appcompat\appcompat\1.2.0\release\res\values\values.xml: Error: Duplicate resources
  [attr/iconTint] D:\studio_workspace\SiHuo\FatAarApp\ModuleC\build\intermediates\exploded-aar\com.google.android.material\material\1.2.1\release\res\values\values.xml	[attr/iconTint] D:\studio_workspace\SiHuo\FatAarApp\ModuleC\build\intermediates\exploded-aar\androidx.appcompat\appcompat\1.2.0\release\res\values\values.xml: Error: Duplicate resources
  [attr/menu] D:\studio_workspace\SiHuo\FatAarApp\ModuleC\build\intermediates\exploded-aar\com.google.android.material\material\1.2.1\release\res\values\values.xml	[attr/menu] D:\studio_workspace\SiHuo\FatAarApp\ModuleC\build\intermediates\exploded-aar\androidx.appcompat\appcompat\1.2.0\release\res\values\values.xml: Error: Duplicate resources
  [attr/backgroundTint] D:\studio_workspace\SiHuo\FatAarApp\ModuleC\build\intermediates\exploded-aar\com.google.android.material\material\1.2.1\release\res\values\values.xml	[attr/backgroundTint] D:\studio_workspace\SiHuo\FatAarApp\ModuleC\build\intermediates\exploded-aar\androidx.appcompat\appcompat\1.2.0\release\res\values\values.xml: Error: Duplicate resources

**Comment by kezong** [comment]
- **Res merge conflicts.** If the library res folder and embedded dependencies res have the same res Id(mostly `string/app_name`). A duplicate resources build exception will be thrown. To avoid res conflicts:
  - consider using a prefix to each res Id, both in library res and aar dependencies if possible. 
  - Adding `android.disableResourceValidation=true` to `gradle.properties` can do a trick to skip the exception, but is not recommended.
