### ISSUE TITLE
proguard.txt in AAR NOT merged！

### ISSUE THREAD

**Issue by douniwan5788** [kezong/fat-aar-android#194]
https://developer.android.com/studio/projects/android-library.html#aar-contents
根据官网文档，AAR里导出的consumerProguardFiles文件名是proguard.txt
代码里却是这么写的：
https://github.com/kezong/fat-aar-android/blob/e0e868fad74b17af9b67b28ee1b1868e20f7256b/source/src/main/java/com/kezong/fataar/AndroidArchiveLibrary.java#L104-L105

实际打包proguard.txt根本没合入啊，跟主页宣传不符

**Comment by kezong** [comment]
Fixed
