### ISSUE TITLE
有人遇到过androidx相关的远程依赖出错的情况吗？

### ISSUE THREAD

**Issue by wsfAAA** [kezong/fat-aar-android#198]

**Comment by zhangbaogithub** [comment]
我遇到了。

build\intermediates\exploded-aar\androidx.appcompat\appcompat\1.2.0\release\res\values\values.xml: Error: Duplicate resources

**Comment by wsfAAA** [comment]
我也是这个情况，你那边有好的解决方案吗？

**Comment by zhangbaogithub** [comment]
不好意思，我刚开始了解这个库，暂时不能给你提供有用的帮助= =

**Comment by wsfAAA** [comment]
我这边的解决方案不好，你可以尝试下不把appcompat库进行合并，接入aar的项目中进行引用， 这样也是可以的。
你要有好的解决方案希望能够分享下，谢谢！=.=

**Comment by zhangbaogithub** [comment]
好的，我试一下

**Comment by NeverMore-Father** [comment]
gradle.properties添加android.disableResourceValidation=true
module下的build.gradle，在defaultConfig下添加 vectorDrawables.useSupportLibrary = true
