### ISSUE TITLE
多个aar的合并打aar失败

### ISSUE THREAD

**Issue by docwei2050** [kezong/fat-aar-android#2]
打包失败后，修改里面的libPackageName为aarPackageName，
 sb << "    public static $type $name = ${aarPackageName}.R.${subclass}.${name};" << '\n'
打包成功，但是在使用打出的fat-aar后，提示资源id找不到。
1.Aaar的activity_a的值是0x7f0f001c，Baar的activity_b的也是0x7f0f001c，合并后，main lib的activity_main的值是0x7f0f001c，，，activity_a的值是0x7f0f001d,，，，activity_b的也是0x7f0f001e,导致资源id找不到。。。

**Comment by kezong** [comment]
不能将libPackageName改为aarPackageName，改了后资源合并就失效了。

能否将修改之前的错误信息发出来，并告知下com.android.tools.build:gradle版本以及gradle的版本。

**Comment by docwei2050** [comment]
您这个插件，亲测两个library合成一个aar是没问题。。如果一个library的lib下有个Aaar，那么合并的时候，Aaar的资源id提示找不到符号

  符号:   变量 layout_behavior
  位置: 类 attr
/Users/Mac/Desktop/testaar/testaar/blibrary/build/intermediates/exploded-aar/r/com/paaa/sppppboard/R.java:31: 错误: 找不到符号
    public static int layout_dodgeInsetEdges = com.paaa.fcaa.blibrary.R.attr.layout_dodgeInsetEdges;
--------------------
  classpath 'com.android.tools.build:gradle:3.2.1'
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip

**Comment by kezong** [comment]
如果在一个library的lib下直接放一个aar会有问题，所有需要合并的aar都需要在lib-main中embed，不然无法合并。建议参考[example](https://github.com/kezong/fat-aar-android/tree/master/example)中的lib-aar-local方式引入本地的aar包，并且如果子library如果需要引用该aar的话可以以compileOnly的形式添加依赖。

**Comment by docwei2050** [comment]
老铁，为啥我的老报

【Fat-aar-INFO】Compile R.class, Dir:/Users/lx/Project/TrainDemo/librarya/build/intermediates/exploded-aar/r
/Users/lx/Project/TrainDemo/librarya/build/intermediates/exploded-aar/r/com/example/secondlib/R.java:5: 错误: 程序包com.example.librarya.R不存在
    public static int abc_fade_in = com.example.librarya.R.anim.abc_fade_in;  这样的R文件id找不到大约有100个错误。   运行sample也是一样啊

**Comment by docwei2050** [comment]
我能加你的Q吗，我的是64939301
