### ISSUE TITLE
主mode的R文件找不到

### ISSUE THREAD

**Issue by hf529270451** [kezong/fat-aar-android#20]
![image](https://user-images.githubusercontent.com/29528761/60590002-764b1780-9dcd-11e9-8726-a26e2cbde4df.png)
我想调用maven-publish 把包上传到私服，报错这个信息，请问可以帮忙看看嘛

**Comment by kezong** [comment]
直接assembleDebug会有问题吗？

**Comment by hf529270451** [comment]
您好，多谢您能抽空回答，我刚才试了试assembleDebug，也是提示R文件找不到，我主model是这么写的您看看，就是isApp为false就是说明这个壳工程是model工程
![image](https://user-images.githubusercontent.com/29528761/60646644-70594300-9e6e-11e9-8c3d-6c241c43dc9f.png)

**Comment by kezong** [comment]
`base`和`model_main`是否有依赖其他的module?
需要将所有需要打包的module都在build.gradle中加上embed才行。
