### ISSUE TITLE
Cannot expand ZIP ****/build/intermediates/compile_only_not_namespaced_r_class_jar/debug/R.jar' as it does not exist.

### ISSUE THREAD

**Issue by RockieLiu** [kezong/fat-aar-android#201]
use AndroidStudio4.1rc, always make failed. i try to create ./compile_r_class_jar/debug/ directory， it seems to work.

**Comment by RockieLiu** [comment]
PC is Macbook

**Comment by kezong** [comment]
what version of `com.android.tools.build:gradle` do you use?

**Comment by RockieLiu** [comment]
version com.android.tools.build:gradle:4.1.0-rc03

**Comment by kezong** [comment]
With gradle plugin 4.1.0, `r class jar` folder has changed to `compile_r_class_jar`.
It will be adapted in the next version.

**Comment by kezong** [comment]
Fix in 1.2.18

**Comment by xmrkwzw** [comment]
still exits in 1.3.6,  because change of the aar outputDir.
