### ISSUE TITLE
Task already exists error on transitive true

### ISSUE THREAD

**Issue by erksch** [kezong/fat-aar-android#204]
Hey there!

Thank you for this aaaaaawesome library!

However, when using `configurations.embed.transitive=true`, I am getting the following error:

```
Cannot add task 'explodeAndroidx.appcompatAppcompatDebug' as a task with that name already exists
```

I saw that you already fixed a [similar issue](https://github.com/kezong/fat-aar-android/issues/48), maybe this can be fixed, too. 

I am using the latest version, latest gradle plugin and version.

Thank you very much!

**Comment by kezong** [comment]
This is usually due to dependency on multiple versions of the Android x library.
It is not recommended to embed the Android x library.
By the way you can try like this:
```java
embed('xxx:1.11.0') {
    exclude(group:'androidx.appcompat')
}
```

**Comment by Siedlerchr** [comment]
For anyone having similar problems:
for me I needed to exclude 
```
      embed('xxx:1.11.0') {
    exclude(group:'androidx.core')
}
```
