### ISSUE TITLE
Cannot invoke method getName() on null object - fat-aar 1.2.19

### ISSUE THREAD

**Issue by something15525** [kezong/fat-aar-android#214]
Hi there,

After upgrading to the latest version, I'm getting this error:

`[fat-aar]--------------------------[common]--------------------------
[fat-aar][embed detected][aar]:<redacted>:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':core'.
> Could not create task ':core:reBundleAarDebug'.
   > Cannot invoke method getName() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
`

Has anyone else had this issue? This happens when running a gradle sync, or running `./gradlew clean` from the command line.

I'll attach the full stacktrace as well.

[gradle-fat-aar-stacktrace.txt](https://github.com/kezong/fat-aar-android/files/5454262/gradle-fat-aar-stacktrace.txt)

**Comment by Sessa93** [comment]
I also have this error, I have seen your commit fixing it. Could you publish a release containing it? Thanks!

**Comment by kezong** [comment]
Try to use 1.2.20
