### ISSUE TITLE
No signature of method: com.kezong.fataar.VariantProcessor.addArtifacts() is applicable for argument types: (java.util.HashSet) values: [[banner-release.aar (:banner-release:)]]

### ISSUE THREAD

**Issue by 123yangu** [kezong/fat-aar-android#217]
No signature of method: com.kezong.fataar.VariantProcessor.addArtifacts() is applicable for argument types: (java.util.HashSet) values: [[banner-release.aar (:banner-release:)]]

**Comment by mobfly** [comment]
这个问题有解么？

**Comment by 123yangu** [comment]
> 这个问题有解么？

升级到最新的版本，并设置gradle.properties的属性android.disableResourceValidation = true
