### ISSUE TITLE
合并多module资源重复

### ISSUE THREAD

**Issue by PiYun01** [kezong/fat-aar-android#22]
我想请问下，不是使用embed 命令才会把资源打包进aar吗？，但是我只embed 一遍appcompatv7b包，但是打包时有很多v7包资源重复的报错

**Comment by PiYun01** [comment]
![zzFNTWUk](https://user-images.githubusercontent.com/14148378/60696762-be775080-9f19-11e9-8546-0c80a4918fad.png)

**Comment by kezong** [comment]
v7包里面涉及了非常多的重复资源，需要在gradle中增加配置来忽略这方面的检查。
1. 在gradle.properties中加上android.disableResourceValidation=true 忽略资源冲突
2. 在build.gradle中加入
```groovy
android {
  defaultConfig {
    vectorDrawables.useSupportLibrary = true
  }

不过不建议将appcompat-v7这样常见且复杂的包利用fat-aar打入整体的aar中，因为一般的apk都会implementation该包，最终会导致冲突。
}
```

**Comment by PiYun01** [comment]
@kezong 感谢你的回答，我现在又遇到一个问题，就是我把moduleA、moduleB打包在主module，但是moudleB implementation moudleA，这时就会编译器就会报重复类的报错，换成moudleB compileOnly moudleA的话，moudleB 就找到不到moudleA的资源文件，请问这种情况改怎么处理

**Comment by kezong** [comment]
如果编译library时，在主module中加上embed moduleA和embed moduleB并不会影响多层依赖中正常依赖，不管是implementation还是compileOnly。
如果编译器提示了类冲突错误，可能确实是有工程本身就有类冲突问题，建议正面解决。

**Comment by qwe134679** [comment]
transitive = true添加该属性后，默认把androidx的包自动打包进去，如何能解决？？

**Comment by luoxiaozeng** [comment]
> @kezong 感谢你的回答，我现在又遇到一个问题，就是我把moduleA、moduleB打包在主module，但是moudleB implementation moudleA，这时就会编译器就会报重复类的报错，换成moudleB compileOnly moudleA的话，moudleB 就找到不到moudleA的资源文件，请问这种情况改怎么处理

您好，请问你这个问题解决了嘛。现在我也遇到了。  aar 嵌套aar 的问题。导致资源文件、类找不到无法引用
