### ISSUE TITLE
fat-aar 生成时会把依赖信息保存下来，当我将打包的aar上传到maven时，会产生一些问题

### ISSUE THREAD

**Issue by Peibalam** [kezong/fat-aar-android#220]
flutter在打包时， fat-aar 生成时会把本地依赖信息保存下来，当我将打包的aar上传到maven时，maven 生成的pom文件会带上这些依赖信息，实际上依赖已经被打包进aar了。那么在别人通过远程依赖来下载这个aar时，就会报无法下载aar中的SNAPSHOT，如果是单独把这个aar作为文件添加依赖的话是没问题的

一下是具体的信息

fluttertoast
thrio
sqflite
package_info
shared_preferences_extend
webview_flutter
path_provider
loggerplugin
get_ip
dartproto
[fat-aar]--------------------------[common]--------------------------
[fat-aar][embed detected][aar]io.flutter.plugins.webviewflutter:webview_flutter:1.0-SNAPSHOT
[fat-aar][embed detected][aar]io.flutter.plugins.pathprovider:path_provider:1.0-SNAPSHOT
[fat-aar][embed detected][jar]io.flutter:flutter_embedding_release:1.0.0-c8e3b9485386425213e2973126d6f57e7ed83c54
[fat-aar][embed detected][jar]io.flutter:armeabi_v7a_release:1.0.0-c8e3b9485386425213e2973126d6f57e7ed83c54
[fat-aar][embed detected][aar]com.yiyou.tt.loggerplugin:loggerplugin:1.0-SNAPSHOT
[fat-aar][embed detected][aar]de.pdad.getip:get_ip:1.0-SNAPSHOT
[fat-aar][embed detected][aar]com.example.FlutterToast:fluttertoast:1.0-SNAPSHOT
[fat-aar][embed detected][aar]com.tekartik.sqflite:sqflite:1.0-SNAPSHOT
[fat-aar][embed detected][aar]com.quwan.tt.shared_preferences_extend:shared_preferences_extend:1.0-SNAPSHOT
[fat-aar][embed detected][aar]io.flutter.plugins.packageinfo:package_info:1.0-SNAPSHOT
[fat-aar][embed detected][aar]com.quwan.tt.flutter.dartproto:dartproto:1.0-SNAPSHOT
[fat-aar][embed detected][aar]com.hellobike.flutter.thrio:thrio:0.5.0

这是pom文件

<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.quwan.tt</groupId>
  <artifactId>flutterModule</artifactId>
  <version>0.0.1</version>
  <packaging>aar</packaging>
  <name>TTFlutterModule</name>
  <description>null</description>
  <licenses>
    <license>
      <name>YourLiceneseName</name>
      <url>http://your.licenese.url</url>
    </license>
  </licenses>
  <developers>
    <developer>
      <id>your_id</id>
      <name>linpeiba</name>
      <email>linpeiba@52tt.com</email>
    </developer>
  </developers>
  <dependencies>
    <dependency>
      <groupId>io.flutter</groupId>
      <artifactId>flutter_embedding_release</artifactId>
      <version>1.0.0-c8e3b9485386425213e2973126d6f57e7ed83c54</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.flutter</groupId>
      <artifactId>armeabi_v7a_release</artifactId>
      <version>1.0.0-c8e3b9485386425213e2973126d6f57e7ed83c54</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.flutter</groupId>
      <artifactId>arm64_v8a_release</artifactId>
      <version>1.0.0-c8e3b9485386425213e2973126d6f57e7ed83c54</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.example.FlutterToast</groupId>
      <artifactId>fluttertoast</artifactId>
      <version>1.0-SNAPSHOT</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.flutter.plugins.packageinfo</groupId>
      <artifactId>package_info</artifactId>
      <version>1.0-SNAPSHOT</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.hellobike.flutter.thrio</groupId>
      <artifactId>thrio</artifactId>
      <version>0.5.0</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.tekartik.sqflite</groupId>
      <artifactId>sqflite</artifactId>
      <version>1.0-SNAPSHOT</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.quwan.tt.shared_preferences_extend</groupId>
      <artifactId>shared_preferences_extend</artifactId>
      <version>1.0-SNAPSHOT</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.flutter.plugins.webviewflutter</groupId>
      <artifactId>webview_flutter</artifactId>
      <version>1.0-SNAPSHOT</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.flutter.plugins.pathprovider</groupId>
      <artifactId>path_provider</artifactId>
      <version>1.0-SNAPSHOT</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.yiyou.tt.loggerplugin</groupId>
      <artifactId>loggerplugin</artifactId>
      <version>1.0-SNAPSHOT</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.quwan.tt.flutter.dartproto</groupId>
      <artifactId>dartproto</artifactId>
      <version>1.0-SNAPSHOT</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>de.pdad.getip</groupId>
      <artifactId>get_ip</artifactId>
      <version>1.0-SNAPSHOT</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>

**Comment by jimneylee** [comment]
哥们，解决没有，我今天也发现这个问题，aar 包合并后，但是走本地 maven 还是提示没有找到依赖包。
```
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find :libuvccommon-release:.
     Required by:
         project :app > com.facebook.react:react-native-webrtc:1.84.0-jitsi-6110239
   > Could not find :libuvccamera-release:.
     Required by:
         project :app > com.facebook.react:react-native-webrtc:1.84.0-jitsi-6110239
```
![Screen Shot 2020-12-08 at 1 14 13 PM](https://user-images.githubusercontent.com/492970/101443005-5ff8a200-3957-11eb-9466-956e973a39ec.png)

**Comment by Peibalam** [comment]
解决了
可以参考下面的方法

afterEvaluate {
    generatePomFileForMavenAarPublication {
        doLast {
            def pomFile = file("../Flutter/build/publications/mavenAar/pom-default.xml")
            if (!pomFile.exists()) {
                return
            }
            //把pom文件中的runtime dependency 都删了 因为这些已经打包进来了
            println pomFile.name
            def xmlparser = new XmlParser()
            Node node = xmlparser.parse(pomFile)
            List<Node> dependencies = node.get("dependencies")
            List<Node> target = new ArrayList<>()
            dependencies.each { dependency ->
                dependency.each { element ->
                    List<Node> scope = element.get("scope")
                    scope.each { _scope ->
                        if (_scope.value().get(0) == "runtime") {
                            if (!target.contains(element)) {
                                target.add(element)
                            }
                        }
                    }
                }
            }

            target.each { targetnode -> targetnode.parent().remove(targetnode) }
            new XmlNodePrinter(new PrintWriter(new FileWriter(pomFile))).print(node)
        }
    }
}

**Comment by zhuangjy24** [comment]
哥们，请教一下 你这个这么用？

**Comment by zhuangjy24** [comment]
@Peibalam 哥们，请教一下 你这个这么用？
