### ISSUE TITLE
ClassNotFoundException: Didn't find class "X" on path - but it's in the APK!

### ISSUE THREAD

**Issue by valeriyo** [kezong/fat-aar-android#221]
In my AAR, I embed the BSON dependency:

```
embed("org.mongodb:bson:4.0.5")
```

Then, my *debug* app using that AAR crashes with:

```
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.bson.BasicBSONDecoder" on path: DexPathList[[zip file "/data/app/~~jUpAzPeM49uAYzgtPo7VDg==/sample_app-DGkMelOAb167cJoC6WfEgQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~jUpAzPeM49uAYzgtPo7VDg==/sample_app-DGkMelOAb167cJoC6WfEgQ==/lib/arm64, /system/lib64, /system/product/lib64]]
```

When I look inside the APK, `BasicBSONDecoder` is there -- in `classes4.dex`:

![image](https://user-images.githubusercontent.com/7052801/98495048-2cf5ae00-21f3-11eb-828b-912d4668e737.png)

I'm puzzled why it cannot be resolved.

When I run *release* AAR+app, minimized and obfuscated with R8, everything works fine.

Any ideas?

**Comment by valeriyo** [comment]
Actually, `public class BasicBSONDecoder implements BSONDecoder` but it looks like `BSONDecoder` is missing... how can this be?

**Comment by kezong** [comment]
set `configurations.embed.transitive = true` in your `build.gradle`

**Comment by valeriyo** [comment]
Nope, did not help at all. This is not a transitive issue. Both `BasicBSONDecoder` and its base interface `BSONDecoder` are in the same library.

**Comment by valeriyo** [comment]
Here is a sample project:
[sampleBson.zip](https://github.com/kezong/fat-aar-android/files/5513163/sampleBson.zip)

It crashes with the error above. Can you help?

**Comment by valeriyo** [comment]
Is this a AGP problem? When library dependency is AAR (which contains `libs\bson-4.0.5.jar`) everything works. When the library dependency is a "project(":library")" -- then APK comes out broken, without BSON classes.
