### ISSUE TITLE
cannot embed project's dependences?

### ISSUE THREAD

**Issue by pikacode** [kezong/fat-aar-android#222]
I'm trying to embed some project:
```
configurations.embed.transitive = true
embed project(path: ':someproj', configuration:'default')
```
but the dependences implemented in `someproj`'s 'build.gradle' didn't been embed.

---
您好，首先非常感谢您提供的第三方插件。我使用了 transitive = true, 但是 embed 的 project 并没有 embed 其中的 implementation。

**Comment by kezong** [comment]
嗯，该属性暂时对本地依赖没有用，只对远程依赖生效。 本地依赖需要全部添加embed.
