### ISSUE TITLE
module调用的问题

### ISSUE THREAD

**Issue by mahaiyun18** [kezong/fat-aar-android#225]
大佬，这种情况  A Module 是要生成aar的，A引入了 B Module，B里面有okhttp、Glide 这样的库，打包aar 后会报okio下的类找不到， okio好像是okhttp里面引入的。同样的 Glide  内部好像也有引入库。请问有方案解决吗，感谢

**Comment by JunlongLiang** [comment]
常用库在引用aar包的工程下implementation就好了啊，一般打包的aar不需要包含这些常用库吧？

**Comment by mahaiyun18** [comment]
嗯  也是
