### ISSUE TITLE
升级到 2.2.19 或 2.2.20 后，打出的aar包少了 **-r-classes.jar 文件

### ISSUE THREAD

**Issue by JunlongLiang** [kezong/fat-aar-android#228]
工程没有改动过的情况下，
升级到 2.2.19 或 2.2.20 后，打出的aar包少了 **-r-classes.jar 文件，导致使用 R.string.xxx，R.style.xxx 的代码报 ClassNotFoundException 错误。
但是降级到 2.2.18 后，打出的 aar 包就有 ***-r-classes.jar 文件，使用也没问题。

**Comment by kezong** [comment]
试试1.3.1版本，R处理换了一种方式，不会再生成r-classes.jar了。
