### ISSUE TITLE
lib的AndroidManifest ${applicationId} 失效

### ISSUE THREAD

**Issue by NicoToast** [kezong/fat-aar-android#23]
fat-aar后lib的AndroidManifest ${applicationId} 会变为lib的包名

example:
 1、lib的包名com.kezong.demo.lib
 2、AndroidManifest 下

   \<provider
      android:authorities="${applicationId}.InitProvider"
      android:exported="false"
      android:name=".InitProvider"/>

3、fat-aar后变为

   \<provider
      android:authorities="com.kezong.demo.lib.InitProvider"
      android:exported="false"
      android:name="com.kezong.demo.lib.InitProvider"/>

4、fat-aar后希望结果：

   \<provider
      android:authorities="${applicationId}.InitProvider"
      android:exported="false"
      android:name="com.kezong.demo.lib.InitProvider"/>

**Comment by kezong** [comment]
感谢反馈，该问题已修复，可以使用1.1.8版本的插件试试。

**Comment by wuyaobang** [comment]
我的gradle插件版本3.0.1 gradle版本4.6 为什么远程依赖com.alibaba:fastjson:1.2.5包加不进去，你的com.facebook.fresco:fresco:1.11.0却可以加进去，是不是一个bug

**Comment by kezong** [comment]
> 我的gradle插件版本3.0.1 gradle版本4.6 为什么远程依赖com.alibaba:fastjson:1.2.5包加不进去，你的com.facebook.fresco:fresco:1.11.0却可以加进去，是不是一个bug

刚试了下，在3.0.1上对jar包的合并有bug，晚一些时间我会修复，建议先用3.1.0+的版本。

**Comment by wuyaobang** [comment]
rebuild 整项目会报错，Error:警告: [options] 未与 -source 1.7 一起设置引导类路径
1 个警告
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib-main:createRsFiledebug'.
> imagepipeline module's AndroidManifest not found

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
备注：gradle 插件版本3.1.0 gradle版本4.6，大神请关注

**Comment by wuyaobang** [comment]
![1562651955(1)](https://user-images.githubusercontent.com/5660973/60863193-78d8c180-a252-11e9-83c5-5ab7035f5458.png)

**Comment by kezong** [comment]
@wuyaobang 你把你的问题新开一个issue吧，我到时候找时间一起处理下。
