### ISSUE TITLE
动态so库打包在jar包中时，开启混淆后so库丢失

### ISSUE THREAD

**Issue by Android500** [kezong/fat-aar-android#231]
如图
![image](https://user-images.githubusercontent.com/15179354/99965200-7affd980-2dcf-11eb-822b-f4905db59863.png)

**Comment by kezong** [comment]
我试了一下最新版1.3.1的插件，是没问题的，jar中class会合并至classes.jar中，so会合并至aar中的jni目录下。
你检查下是否有添加packagingOptions将so给exclude了。

如果还有问题，建议将Gradle和AGP升级试试。
