### ISSUE TITLE
aar的资源问题

### ISSUE THREAD

**Issue by aprz512** [kezong/fat-aar-android#239]
假如模块使用的A版本的Support库中有资源文件res1，而接入方App使用了更高版本的Support库中没有res1这个资源，那么App构建生成的R文件中将没有res1这个资源索引，可是我们打入AAR中的R文件还保留着对res1的符号引用，结果就是在运行时类初始化失败（R.class的<cinit>错误）：

```java
public final class R {
  public static final class string {
    //这里的com.main.library.R.string.res1被过滤掉不再存在，符号引用失效
    public static int res1 = com.main.library.R.string.res1;
    }
}
```

有考虑将这种“桥接”的方式改成使用字节码修改的方式吗？
比如，某个依赖中是这样使用R 的
```java
import com.lib.R.layout;

public class A {
        static {
            sKeys.put("layout/slbase_activity_camera_web_0", layout.slbase_activity_camera_web);
        }
}
```
经过 transform 后，会变成下面的样子：
```java
// 这里包名变了
import com.aar.R.layout;

public class A {
        static {
            sKeys.put("layout/slbase_activity_camera_web_0", layout.slbase_activity_camera_web);
        }
}
```
就是使用 transform 将所有依赖的 R 文件的包名改成 aar 的R包名。这样可以避免字段失效问题，就不用为每个依赖生成 R 文件，以及打对应的 jar 包了。

**Comment by kezong** [comment]
这个问题可以试试将gradle plugin升级到3.6.0以上。

有人之前提出了一样的想法 #184 ，不过我最近比较忙，还没时间研究，如果你有兴趣的话，非常欢迎PR。

**Comment by aprz512** [comment]
我提了一个pr

**Comment by aprz512** [comment]
gradle plugin 升级到 3.6.4，字段问题确实没有了
