### ISSUE TITLE
关于3.0.1版本兼容问题

### ISSUE THREAD

**Issue by wuyaobang** [kezong/fat-aar-android#24]
1、3.0.1gradle插件和4.6gradle，远程依赖打不进arr中
2、整个项目rebuild的时候， 整项目会报错，Error:警告: [options] 未与 -source 1.7 一起设置引导类路径
1 个警告
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':lib-main:createRsFiledebug'.
imagepipeline module's AndroidManifest not found
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 6s
备注：gradle 插件版本3.1.0 gradle版本4.6，大神请关注

**Comment by wuyaobang** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':communitysdk:generateDebugRFile'.
> com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: 1 字节的 UTF-8 序列的字节 1 无效。

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

93 actionable tasks: 7 executed, 86 up-to-date
大神 合并的时候这个报错是什么意思？

**Comment by wuyaobang** [comment]
整个项目rebuild的时候，arr包都会报module's AndroidManifest not found，请大神优化

**Comment by kezong** [comment]
> 整个项目rebuild的时候，arr包都会报module's AndroidManifest not found，请大神优化

现在看上去./gradlew clean assemble一起调用会有问题，我有时间的会优化该问题，你先clean和assemble分开执行吧。

修复后我会回复该issue

**Comment by kezong** [comment]
1、3.0.1gradle插件和4.6gradle，远程依赖打不进arr中
该问题已在1.1.10版本中修复

2、整个项目rebuild的时候， 整项目会报错，Error:警告: [options] 未与 -source 1.7 一起设置引导类路径
该警告是因为的电脑jdk环境与工程compileOptions不匹配导致，属于工程问题，可以自行更改

3、整个项目rebuild的时候，arr包都会报module's AndroidManifest not found，请大神优化
该问题已在1.1.10版本中修复
