### ISSUE TITLE
上传到Maven时R.class未打入AAR

### ISSUE THREAD

**Issue by joevess** [kezong/fat-aar-android#241]
已经更新到最新版本 classpath 'com.kezong:fat-aar:1.2.19'.

configurations.embed.transitive = true

afterEvaluate { project ->
    uploadArchives{
        repositories{
            mavenDeployer {
                repository(url:MAVEN_LOCAL_PATH ){
                    authentication(userName: USERNAME, password: PASSWORD)}
                pom.artifactId = ARTIFACT_ID
                pom.groupId = GROUP_ID
                pom.version = project.android.defaultConfig.versionName
                pom.withXml {
                    def dependenciesNode = asNode().appendNode('dependencies')
                    configurations.api.allDependencies.each { dependency ->
                        def dependencyNode = dependenciesNode.appendNode('dependency')
                        dependencyNode.appendNode('groupId', GROUP_ID)
                        dependencyNode.appendNode('artifactId', ARTIFACT_ID)
                        dependencyNode.appendNode('version', version)
                    }
                }
            }
        }
    }
}

**Comment by kezong** [comment]
这个问题1.2.19应该是修复了，你试试升级到1.2.20
