### ISSUE TITLE
com.android.tools.build:gradle not found in buildscript classpath

### ISSUE THREAD

**Issue by matiasdelbel** [kezong/fat-aar-android#243]
I'm using Kotlin DSL, and in my `build.gradle.kts` inside the `buildSrc` folder I have defined:

```kotlin
dependencies {
    implementation("com.android.tools.build:gradle:3.5.3")
    ...
    implementation("com.kezong:fat-aar:1.2.20")
}
```

But when I try to sync the project, the following error is being thrown: `Cause: com.android.tools.build:gradle not found in buildscript classpath`

Is there a way to use the plugin without changing my previous config? I [saw](https://github.com/kezong/fat-aar-android/blob/master/source/src/main/groovy/com/kezong/fataar/FatLibraryPlugin.groovy#L150) that the plugin search the dependency in the `classpath` config...

**Comment by kezong** [comment]
Fixed in plugin 1.3.1
