### ISSUE TITLE
library 中使用 productFlavors 有部分 jar 包没有打进libs目录

### ISSUE THREAD

**Issue by zhangbaogithub** [kezong/fat-aar-android#244]
调试看了下，是 VersionAdapter 这个类中 getLibsDirFile 这个方法获取到的路劲不对，mVariant.dirName 改成 mVariant.name就可以了

**Comment by kezong** [comment]
环境发下
 - Gradle Plugin Version: 
 - Gradle Version: 
 - Fat-aar Version:

**Comment by zhangbaogithub** [comment]
Gradle Plugin Version: 4.1.1
Gradle Version: 6.5
Fat-aar Version: 1.3.1

**Comment by kezong** [comment]
AGP 3.6以上Jar路径错误，这个问题1.2.17后已经修了。
1.3.1版本应该不会有问题。

https://github.com/kezong/fat-aar-android/blob/33853ff6054a83d88b34ff0fdd54ba676388a7f6/source/src/main/groovy/com/kezong/fataar/VersionAdapter.groovy#L53-L61
