### ISSUE TITLE
可以提pr吗

### ISSUE THREAD

**Issue by SusionSuc** [kezong/fat-aar-android#253]
谢谢作者提供这么好的项目！

我在实际业务使用过程中，发现了一些阻塞的问题，于是clone的一份工程做了一些修改，现在想把这些修改提过来，不过我看不能创建新的PR？

**Comment by kezong** [comment]
非常欢迎 PR

**Comment by kezong** [comment]
我没有对PR进行限制，你遇到了什么问题？

**Comment by SusionSuc** [comment]
sorry  还没给开源库提过pr， 我知道怎么操作了
