### ISSUE TITLE
No static field oc_icon_sort of type I in class Lcom/oppo/store/sdk/R$drawable

### ISSUE THREAD

**Issue by PiYun01** [kezong/fat-aar-android#26]
运行Demo的时候报的异常，可以看到aar包里是有这个资源的，但是R文件里没有生成这个id

**Comment by kezong** [comment]
1. 提供下编译aar时的gradle plugin和gradle版本
2. 查看aar中的R.txt文件下是否有该id
3. 查看aar中libs/目录下是否有r-classes.jar文件，并且里面是否包含该包名下的资源id
4. 查看oc_icon_sort所在的包和demo引用的包是否匹配

**Comment by charles-yinyu** [comment]
可能部分第三方库用老的版本（包含oc_icon_sort）编译，R.txt里会包含该id，但集成到主工程时用的新的版本，不包含该资源，导致找不到这个资源。
我在插件的crateRFile里修改了资源ID的代理方式，通过反射检查是否存在，如下示
                sb << "    public static final $type $name = existAndGet(${libPackageName}.R, ${subclass}.${name});" << '\n'

@kezong 楼主看有更好的方式吗

**Comment by kezong** [comment]
@charles-yinyu 在新版本中，我尝试解决了这类似的问题，试试1.2.3版本是否有解决该问题。

**Comment by charles-yinyu** [comment]
@kezong 问题还是没有解决

原因是你是通过主library里的symbolMap去排查是否存在，但主library依赖的support包可能是低版本(25)，APK集成的是高版本28，25的资源id会进入到R.txt，所以在symbolMap里是肯定存在的；
fataar的R文件是在APK生成时创建的，打fataar包时是不知道依赖的资源是否真实存在，所以我觉得判断过程应该是在APK生成过程中，去修改fataar里的R文件；

java.lang.NoSuchFieldError: No static field abc_action_bar_view_list_nav_layout of type I in class Lmg/rbt/R$layout; or its superclasses (declaration of 'mg.rbt.R$layout' appears in /data/app/cmccwm.mobilemusic-vPfTr5Z-AgBjr9exDFh8uQ==/base.apk:classes2.dex)

**Comment by kezong** [comment]
看看是否在library中使用了support 25有但是28没有的类或者资源，如果使用了的话，照理说不使用fat-aar的话，也会运行错误的。

**Comment by kezong** [comment]
@charles-yinyu 我复现了该问题，这个版本确实会存在这种问题。
现在推荐的解决办法是：
- 在主library引用support的包的时候，使用`compileOnly`，不要用`implementation`或者`api`。

我在后续版本中也会尝试修复该问题

**Comment by kezong** [comment]
@charles-yinyu 重新提一个issue吧，我到时候修复了在那里回复，这个issue和你报这个不太一样，属于两个问题
