### ISSUE TITLE
反复build，会导致release中的jni包丢失

### ISSUE THREAD

**Issue by donyang** [kezong/fat-aar-android#27]
反复build，会导致release中的jni包丢失 1.1.10， 1.1.8都是这样

**Comment by donyang** [comment]
outputs/aar-R/release/jni 有时有有时没有，很不稳定

**Comment by kezong** [comment]
刚试了下，确实有问题，我会抽时间修复。

先暂时用./gradlew assembleDebug或者./gradlew assembleRelease 单独输出debug包和release包吧。

**Comment by kezong** [comment]
在1.1.11版本中已修复该问题

**Comment by liugangnhm** [comment]
依然存在问题，不管是最新版本1.2.11还是1.1.11
