### ISSUE TITLE
VirusTotal查毒过不了

### ISSUE THREAD

**Issue by 87926042** [kezong/fat-aar-android#280]
**Describe the issue**
新版本编译后用VirusTotal查毒，发现MaxSecure会报毒，一个一个试之后发现1.2.20版本正常。

**Build Environment**
 - Operating System: [e.g. MacOS]
 - Gradle Plugin Version: [e.g. 4.1.2]
 - Gradle Version: [e.g. 6.5]
 - Fat-aar Version: [e.g. 1.3.1]

**Comment by kezong** [comment]
建议反馈给VirusTotal
该插件没有使用任何恶意功能，并且是开源软件，可以阅读源码查看哪里报毒。
