### ISSUE TITLE
单独embed一个jar包，会打不进aar，发现有个地方有问题

### ISSUE THREAD

**Issue by PengZeHai** [kezong/fat-aar-android#288]
![a](https://user-images.githubusercontent.com/16265449/112604054-b62f1980-8e50-11eb-97cd-ffc3df2adb5f.png)
这里少了个mJarFiles.isEmpty判断

**Comment by kezong** [comment]
感谢反馈。

**Comment by threedeer** [comment]
这个问题已经解决了吗？我现在就是一个单独的jar想打进aar，但是没成功
