### ISSUE TITLE
Supporting AGP 4.2.0-alpha07+

### ISSUE THREAD

**Issue by powerserg17-bunch** [kezong/fat-aar-android#290]
**Describe the issue**
AGP version 4.2.0-alpha07+ fails with 
```
Execution failed for task ':sdk-android:processReleaseManifest'.
> java.io.FileNotFoundException: /Users/powerserg/merging/sdk-android/build/intermediates/library_manifest/release/AndroidManifest.xml (No such file or directory)
```
`AndroidManifest.xml` is found in`${mProject.buildDir.path}/intermediates/merged_manifest/${mVariant.name}/AndroidManifest.xml` instead of `${mProject.buildDir.path}/intermediates/library_manifest/${mVariant.name}/AndroidManifest.xml`.

Copying the entire plugin into `buildSrc` and manually changing the `manifestOutput` completely fixes the issue. 
Found this [issue](https://github.com/kezong/fat-aar-android/issues/147), not sure if that's related, unfortunately I don't have supporting references to the changes in the AGP to tell that my solution is 100% appropriate. Please advise. Thank you. 

**Build Environment**
 - Operating System: MacOS
 - Gradle Plugin Version: 4.2.0-beta06
 - Gradle Version: 6.7.1
 - Fat-aar Version: 1.3.5

**Comment by kezong** [comment]
Good job, Thanks for feedback.
This is not a big change, I hope you can pull request for this issue.
