### ISSUE TITLE
lib下有aar时打包aar，资源文件会冲突

### ISSUE THREAD

**Issue by hqglichao** [kezong/fat-aar-android#3]
如果要打包的aar包含另一个aar的时候，资源文件如果两者中都有的话，会报资源文件冲突。
比如两者都有strings.xml，就会报Error: Duplicate resources

**Comment by kezong** [comment]
可参考README中所写的资源冲突处理办法：
* **Res merge conflicts.** If the library res folder and embedded dependencies res have the same res Id(mostly `string/app_name`). A duplicate resources build exception will be thrown. To avoid res conflicts:
  * consider using a prefix to each res Id, both in library res and aar dependencies if possible. 
  * Adding "android.disableResourceValidation=true" to "gradle.properties" can do a trick to skip the exception, but is not recommended.

**Comment by hqglichao** [comment]
多谢，亲测有效

**Comment by andoter0501** [comment]
android.disableResourceValidation=true 是有效的
