### ISSUE TITLE
多module依赖，引用aar时报错，找不到底层module的基础类。

### ISSUE THREAD

**Issue by lhs21** [kezong/fat-aar-android#31]
我的程序是这样的: 主module A 依赖 module B 和module C 。module B 也依赖module C,  在打包aar时，在主moduleA中加上了embed module B和embed module C ，module B 中对module C的依赖仍沿用 implementation，打包也显示成功。但是引用aar后，使用aar内的功能时闪退，报错如下：
java.lang.NoClassDefFoundError : Failed resolution of : Lcom/serenegiant/common/BaseActivity
这个BaseActivity也就是 module C的基础类。module A 里有import该类，module B没有import该类。同时，我发现aar里的class.jar 里打包进去了 该类，却总报错找不到。想请问一下这个问题有没有什么思路解决，是否是我使用插件不正确，或者这种多层依赖不支持。困惑我好几天，多谢指教！！

**Comment by lhs21** [comment]
还有一个细节，我的module C里有jni和.so文件，但是最终打包出来的aar里，没有.so 文件和jni

**Comment by kezong** [comment]
提供一下使用的fat-aar版本、gradle plugin版本、gradle版本以及使用的操作系统环境；

**Comment by lhs21** [comment]
fat-aar的版本是 1.1.8（我试过最新的1.1.11和1.1.10，均报错说Could not find com.kezong:fat-aar:1.1.11）
gradle plugin 版本为 4.10.1     gradle版本为 3.3.2   操作系统环境为 windows 10（64位）， android studio 版本为3.2

**Comment by kezong** [comment]
so的合并之前也有使用windows系统的开发者报过，你可以看看1.1.11版本是否有解决，我这缺少windows电脑，所以暂时没有跟进这个问题；

关于NoClassDefFoundError，你可以看看BaseActivity继承的接口或者类是否有被embed进包里了。

还有你可以将java.lang.NoClassDefFoundError : Failed resolution of : Lcom/serenegiant/common/BaseActivity这个Exception的所有日志贴上来吧，信息应该会更多一些。

**Comment by lhs21** [comment]
之前尝试1.1.11报错，找不到：com.kezong：fat-aar：1.1.11，已解决,给android studio设置代理，使用jcenter()即可，不替换为国内的镜像。使用1.1.11版本后， .so 文件成功打包进去，但依旧报错，错误不变。

BaseActivity继承的类为AppCompatActivity，应该不用嵌入包里吧。

java.lang.NoClassDefFoundError的日志如下：
![D4W$VDLZ1 5BRA(`_HTWSR3](https://user-images.githubusercontent.com/27982354/61422113-d220af00-a93c-11e9-96f0-ed2e439d6e1d.png)
![1(NFT)QYT}%NUA@L)277936](https://user-images.githubusercontent.com/27982354/61422119-d947bd00-a93c-11e9-9f53-2fb30bc35233.png)

**Comment by kezong** [comment]
从错误日志来看，BaseActivity加载错误是由于`com.serenegiant.dialog.MessageDialogFragmentV4$MessageDialogListener`该类没有找到，你查查这个吧，看看这个库是否没有引入。

**Comment by lhs21** [comment]
解决了！！多谢提醒！！！非常感谢
