### ISSUE TITLE
libs中引用的jar包中包含assets目录，最终的libs中的jar包中丢失了assets目录

### ISSUE THREAD

**Issue by allenaware** [kezong/fat-aar-android#32]

**Comment by kezong** [comment]
在jar包所在的build.gradle将minifyEnabled打开，assets会保留在classes.jar中，你可以试试。

**Comment by hzl123456** [comment]
但是如果不想开启 minifyEnabled ，有其他办法可以将ibs中引用的jar包中包含assets目录打包的时候保留么

**Comment by cloudending** [comment]
请问这个解决了吗，现在库里面引用了一个jar，jar里面包含assets目录，但是最终打包出来的aar里面没有jar包中的assets

**Comment by kezong** [comment]
jar包中的assets会合并至classes.jar中，并不在jar中，你们仔细看看。

**Comment by kezong** [comment]
1.3.1支持了该特性，试试最新版本。
