### ISSUE TITLE
embed的依赖有的时候打不进去

### ISSUE THREAD

**Issue by xll970211** [kezong/fat-aar-android#320]
gradle 6.0+
fat-aar 1.3.3+
When I build for the first time, I can successfully type embedded dependency into AAR, but when I build for many times, sometimes I can't type embedded dependency into AAR

当我第一次build的时候，我可以将embed的内容打进包内，但是再次build的时候可能无法将embed的依赖打进包内。但是当我切换gradle版本的时候就又可以成功build

**Comment by zhubinsheng** [comment]
qaq~

**Comment by zhubinsheng** [comment]
beacause https://github.com/kezong/fat-aar-android/pull/240/files
