### ISSUE TITLE
java.util.zip.ZipException: duplicate entry: META-INF/versions/9/module-info.class

### ISSUE THREAD

**Issue by abhishekImpressico** [kezong/fat-aar-android#325]
**Issue Description**
I want to package all dependencies of my Library into .aar file and I am able to see all dependencies in libs folder of .aar file (checked by extracting it). But when I used resulting .aar file in sample project, I am getting below build error:

Execution failed for task ':app:checkDebugDuplicateClasses'.
Could not resolve all files for configuration ':app:debugRuntimeClasspath'. Failed to transform MyMobileSDK-debug-.aar (:MyMobileSDK-debug:) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.status=integration, org.gradle.usage=java-runtime}. > Execution failed for AarToClassTransform: /home/abhishek.kumar/AndroidStudioProjects/sdk-api-android/app/libs/MyMobileSDK-debug.aar. > duplicate entry: META-INF/versions/9/module-info.class

Any help or guidance will be well appreciated. Thanks.

**Build Environment**
 - Operating System: Ubuntu 18.04
 - Gradle Plugin Version: 4.2.1
 - Gradle Version: 6.7.1
 - Fat-aar Version: 1.3.6
 - Android Studio: 4.2.1

**Comment by TangStudio** [comment]
I have the same problem,Any help or guidance will be well appreciated. Thanks.

**Comment by TangStudio** [comment]
I use kotlin version 1.5,and this is my build environment:

Operating System: Windows10
Gradle Plugin Version: 4.2.1
Gradle Version: 6.7.1
Fat-aar Version: 1.3.6
Android Studio: 4.2.1

**Comment by TangStudio** [comment]
> **Issue Description**
> I want to package all dependencies of my Library into .aar file and I am able to see all dependencies in libs folder of .aar file (checked by extracting it). But when I used resulting .aar file in sample project, I am getting below build error:
> 
> Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'. Failed to transform MyMobileSDK-debug-.aar (:MyMobileSDK-debug:) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.status=integration, org.gradle.usage=java-runtime}. > Execution failed for AarToClassTransform: /home/abhishek.kumar/AndroidStudioProjects/sdk-api-android/app/libs/MyMobileSDK-debug.aar. > duplicate entry: META-INF/versions/9/module-info.class
> 
> Any help or guidance will be well appreciated. Thanks.
> 
> **Build Environment**
> 
> * Operating System: Ubuntu 18.04
> * Gradle Plugin Version: 4.2.1
> * Gradle Version: 6.7.1
> * Fat-aar Version: 1.3.6
> * Android Studio: 4.2.1

I may know what the problem is. One of the third party open source libraries uses something from JDK9

**Comment by abhishekImpressico** [comment]
@TangStudio 
I am using below dependencies in my library project to create aar file
    embed 'io.reactivex.rxjava3:rxandroid:3.0.0'
    embed 'io.reactivex.rxjava3:rxjava:3.0.0'
    embed "com.squareup.okhttp3:okhttp:4.9.1"
    embed "com.squareup.okhttp3:logging-interceptor:4.9.1"
    embed "com.squareup.retrofit2:retrofit:2.9.0"
    embed "com.squareup.retrofit2:converter-gson:2.9.0"
    embed "com.squareup.retrofit2:adapter-rxjava3:2.9.0"
    embed 'com.google.android.instantapps:instantapps:1.1.0'
    embed 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'

Not able to figure out which third party open source library uses something from JDK9

**Comment by abhishekImpressico** [comment]
@TangStudio I figured out the third party open source library behind my issue: com.squareup.okhttp3:logging-interceptor:4.9.1

I have used 'transitive = false' for it to solve build issue like 
embed ("com.squareup.okhttp3:logging-interceptor:4.9.1") {
    transitive = false
}
