### ISSUE TITLE
embed的aar manifest中有中文注释时，编译问题

### ISSUE THREAD

**Issue by TsmileAssassin** [kezong/fat-aar-android#34]
embed的aar manifest中有中文注释时，merge出来的manifest中有乱码，应该是编码问题。
出现 2 字节的 UTF-8 序列的字节 2 无效。

**Comment by TsmileAssassin** [comment]
应该是windows才有的问题，mac不会有。

**Comment by kezong** [comment]
可以试试1.2.3版本是否有解决该问题

**Comment by TsmileAssassin** [comment]
已经ok，谢谢
