### ISSUE TITLE
Release latest changes to Maven Central

### ISSUE THREAD

**Issue by GabrielBottari** [kezong/fat-aar-android#348]
New changes we're recently made to support the library with Gradle version 7.0.2+. It is currently not available on the latest release, as it dates back a few months. Can we have a new version released on Maven Central? @kezong 

Thank you!

**Comment by DDeg** [comment]
I use plugin built from PR#341 on pretty large project. Works fine on AGP 7.0.3 + Gradle 7.2 for a while now, aar and jar includes correctly.

**Comment by Judas** [comment]
@DDeg Have you been able to test/reproduce the issue ?
@kezong would you have some time to review the PR to check if the proposed workaround is relevant ?

**Comment by GabrielBottari** [comment]
For some reason, it seems to work for me right now for gradle `7.0.2` for the latest release `1.3.6`. I'll keep testing and let you guys know if it breaks again.

**Comment by FDuhen** [comment]
Bump, having the issue described here with Gradle `7.2` and AGP `7.1.0`, a release would be appreciated

**Comment by kezong** [comment]
Released in version 1.3.7
