### ISSUE TITLE
关于/resources/META-INF/services中的文件没有合并的问题

### ISSUE THREAD

**Issue by RavenLiao** [kezong/fat-aar-android#349]
使用ServiceLoader机制时, 在主模块中发现无法找到embed的包中的类, 经过反编译查看, embed的包的/META-INF/services的文件没有被合并到最后生成主模块中的aar中, 希望可以加上.

注: 经测试发现, 实现将/META-INF/services中的文件先写到主模块的/META-INF/services文件中, 再进行打包, 程序可以正常实现功能.

**Comment by andoter0501** [comment]
mark+1

**Comment by njzhangsan2013** [comment]
这个问题请问有没有解决办法

**Comment by ljphawk** [comment]
> 这个问题请问有没有解决办法

请问解决了吗

**Comment by njzhangsan2013** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by njzhangsan2013** [comment]
> > 这个问题请问有没有解决办法
> 
> 请问解决了吗

自己改下源码，本地依赖插件解决了

**Comment by ljphawk** [comment]
> > > 这个问题请问有没有解决办法
> > 
> > 
> > 请问解决了吗
> 
> 自己改下源码，本地依赖插件解决了

能否贴下改动的地方呀
