### ISSUE TITLE
support包资源id在fataar的R文件中未生成：No static field abc_action_bar_view_list_nav_layout of type I in class Lmg/rbt/R$layout

### ISSUE THREAD

**Issue by charles-yinyu** [kezong/fat-aar-android#36]
主library依赖的support包可能是低版本(25)，APK集成的是高版本28，25的资源id会进入到R.txt，所以在symbolMap里是肯定存在的；
fataar的R文件是在APK生成时创建的，打fataar包时是不知道依赖的资源是否真实存在，所以我觉得判断过程应该是在APK生成过程中，去修改fataar里的R文件；

java.lang.NoSuchFieldError: No static field abc_action_bar_view_list_nav_layout of type I in class Lmg/rbt/R$layout; or its superclasses (declaration of 'mg.rbt.R$layout' appears in /data/app/cmccwm.mobilemusic-vPfTr5Z-AgBjr9exDFh8uQ==/base.apk:classes2.dex)

**Comment by kezong** [comment]
该问题是由于application和主library中的support不匹配所导致。

目前有两个办法可以解决：
1. 在application和library中使用同一版本的support库
2. 在主library引用support的包的时候，使用`compileOnly`，不要用`implementation`或者`api`。

我在后续版本中也会尝试修复该问题

**Comment by q644899972** [comment]
@kezong 
同样的问题  但我的主library和application的support库是版本一致的 都是28.0.0 
 java.lang.NoSuchFieldError: No static field glide_custom_view_target_tag of type I in class Lcom/jiayu/online/taotutu_route/R$id; or its superclasses (declaration of 'com.jiayu.online.taotutu_route.R$id' appears in /data/app/com.jiayu.online.myapplication2-cMja5_vGFh7v4n-8hmgnBw==/base.apk!classes2.dex)

**Comment by kezong** [comment]
@q644899972 你这个不是support库的问题，是Glide库问题，如果不需要将Glide库打包的话，在主library中将Glide换成`compileOnly`吧。

**Comment by zsweigart** [comment]
I am having the same issue
```
java.lang.NoSuchFieldError: No static field abc_action_bar_view_list_nav_layout of type I in class L.../.../.../R$layout; or its superclasses (declaration of `...R$layout' appears in /data/app/...-sCFndi5xh4Xu3VqslcWdTg==/base.apk)
        at ....R$layout.<clinit>(R.java:761)
```

**Comment by kezong** [comment]
@zsweigart use `compileOnly` instead of `implementation` in main lib

**Comment by docwei2050** [comment]
abc_action_bar_view_list_nav_layout  再次遇到这个问题，实际上我已经强制将支持库版本指定为28，但是还是会出现这个找不到，，，R文件中的这个到底是怎么生成的？？？导致我在运行的时候，找不到这个id

**Comment by 123yangu** [comment]
我这边也是一样的错误java.lang.NoSuchFieldError: No static field abc_btn_rating_star_off_mtrl_alpha of type I in class，实际上lib包使用compileOnly，打包会报错，只能换成implementation才能打包成功，support库都是统一改成了v27.1.1,还是会报错，实际报错的位置就是生成了一个R.class造成的，里面有些ID根本是没有的
