### ISSUE TITLE
1.2.3 windows上无法将jni和assets打入fataar

### ISSUE THREAD

**Issue by huoxinchi** [kezong/fat-aar-android#37]
如题 1.1.11是可以的 ，切换到1.2.3 就有问题

**Comment by kezong** [comment]
./gradlew clean一下试试

**Comment by huoxinchi** [comment]
清理重启这些肯定都做了 ，反复切换这俩版本一直这样

**Comment by llDavidll** [comment]
Hi,

First, I'm sorry if I misunderstood something, I do not speak chinese so I used google translate to search in already created issues.

I'm just starting to use your plugin with version 1.2.3 and noticed jni libraries from aar dependencies were not included. I'm also using windows, and I tested with a simple use case :

`embed 'com.google.ar:core:1.10.0`

The classes and resources are well included, but no JNI folder is created in the output aar. I never used another version of your plugin before.

After seing this issue I tried the same code with version 1.1.11, and the JNI libraries are included.

If you need me to test something, feel free to ask.

Android gradle plugin / Android Studio : 3.4.2
Gradle : 5.5

**Comment by kezong** [comment]
@huoxinchi @llDavidll  Good issue!
I fix this bug in `1.2.4`.

**Comment by huoxinchi** [comment]
嗯 我已经自己跟踪修复了和你修改差不多，不过为什么mac 可以 感觉比较奇怪，俩平台编译流程略有不同？
