### ISSUE TITLE
Classes not exposed on release aar with minifyEnabled 

### ISSUE THREAD

**Issue by wishygupta** [kezong/fat-aar-android#376]
**Describe the issue**
Classes not exposed on release aar with minifyNeabled set as true

**Build Environment**
 - Operating System: [MacOS]
 - Gradle Plugin Version: [7.1.2]
 - Gradle Version: [7.2]
 - Fat-aar Version: [ 1.3.8]

I created a sample app with 2 library modules.
The link is here [Fat Arr Sample](https://github.com/wishygupta/FatArrSample)
Enabled minify for both lib1 and lib2 modules.  Also added proguard rules
The final release aar doesn't contain the classes declared on proguard.

**Comment by JOikarinen** [comment]
I have noticed this same issue on my project.

**Comment by wishygupta** [comment]
This can be solved using proguard rules.
Add your classes to be exposed in proguard of ur library module.
Another way is to use annotation `@Keep`
