### ISSUE TITLE
关于example编译错误的问题

### ISSUE THREAD

**Issue by hewind** [kezong/fat-aar-android#38]
下载example导入studio中，报错如下：
WARNING: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
根据网上查到的资料说是使用了过时的api，想问下作者，这个问题该怎么解决呢？

**Comment by kezong** [comment]
该接口并不是插件直接调用引起，是系统调用了过时的接口所致。
目前不会影响编译，之后版本官方应该会解决，我也会看看有没有替代的办法。

**Comment by hewind** [comment]
好的，感谢回复，这边clean rebuild后项目正常了。
