### ISSUE TITLE
1.2.3上打包，子module依赖support v4，最终打出的包把support包的attr定义打入了。运行时报错

### ISSUE THREAD

**Issue by TsmileAssassin** [kezong/fat-aar-android#40]
这是我依赖support v4的module的R文件中会有下面这些应该是support包中定义的，如下。实际运行时会报找不到这些attr
public static final class styleable {

public static final int[] ColorStateListItem;
public static final int ColorStateListItem_alpha;
public static final int ColorStateListItem_android_alpha;
public static final int ColorStateListItem_android_color;
public static final int[] CoordinatorLayout;
public static final int CoordinatorLayout_keylines;
public static final int CoordinatorLayout_statusBarBackground;
public static final int[] CoordinatorLayout_Layout;
public static final int CoordinatorLayout_Layout_android_layout_gravity;
public static final int CoordinatorLayout_Layout_layout_anchor;
public static final int CoordinatorLayout_Layout_layout_anchorGravity;
public static final int CoordinatorLayout_Layout_layout_behavior;
public static final int CoordinatorLayout_Layout_layout_dodgeInsetEdges;

**Comment by kezong** [comment]
该问题是由于library和application引用的support包版本不一致导致。
你可以选择在library中对support包采用`compileOnly`的依赖方式解决该问题，或者采用相同的版本。

**Comment by charles-yinyu** [comment]
如果是自己的工程代码，可以采用compileOnly的方式，但大量的第三方库，与主工程的support版本不一致，老版本的id或者attr会随着第三方AAR带入到主library的R.txt文件中，导致运行时找不到资源id。
非fataar情况下，系统打apk包时不管资源是否存在，都会给不存在的id分配值，只是不会用到，所以不会出问题

**Comment by kezong** [comment]
fataar的资源合并方案目前不支持分配了id但不使用的情况，具体原因可以参考源码。

不是所有的library采用都需要采用`compileOnly`，只需要在使用embed的主library依赖support的时候采用`compileOnly`就行，如果主library没有直接使用到support，甚至可以不依赖support包。

现在只对library做了R.txt检测，未来会考虑做资源检测，如果资源不存在就不会生成该id，这一块比较复杂，目前仍然规划中，在后期的版本会加上。

**Comment by TsmileAssassin** [comment]
我在主library将support包的implemention 改成compileOnly，没有问题了，这样可以解决。
我看了下dependency，我之前确实只有一个公共的子module依赖support包。
