### ISSUE TITLE
Issue in larger size aar than combined one

### ISSUE THREAD

**Issue by himgupta229** [kezong/fat-aar-android#41]
Hi,

I am using your plugin. My use case is as below:

I am developing one module 'lib1' which internally uses a third party aar 'lib2'.I want to merge that 'lib2' into my codebase so that our merchant can import 'lib1' and get working.
'lib2' internally uses 'raw' asset. I merged the two codebases using your plugin as an example of "lib-aar-local".For merging, I ran the task **assembleRelease** in Android Studio. When I analyzed the merged aar I found that some code base also comes in libs folder whereas those files weren't visible when I individually analyze "lib2".Actually, that libs folder content is increasing the size of my fat aar .Can I skip that libs folder content somehow?

**Comment by kezong** [comment]
What are the extra files in libs folder?
` r-classes.jar` is generated by the plugin and cannot be deleted.

**Comment by himgupta229** [comment]
> What are the extra files in libs folder?
> ` r-classes.jar` is generated by the plugin and cannot be deleted.

Yes r-classes.jar is the folder but why this folder contents are not visible when I am analyzing "lib2"

**Comment by himgupta229** [comment]
Actually, I thought that the combined fat aar size would be my aar size plus the "lib2" aar size but in reality it is bigger than that.

**Comment by kezong** [comment]
You can read the source code. `r-classes.jar` is generated by plugin for merging and mapping resources. It should be a relatively small size, it is necessary.

**Comment by himgupta229** [comment]
> You can read the source code. `r-classes.jar` is generated by plugin for merging and mapping resources. It should be a relatively small size, it is necessary.

But why I can't see them in lib2 after extraction?

**Comment by kezong** [comment]
It was generated when building `lib1`
