### ISSUE TITLE
运行demo报错

### ISSUE THREAD

**Issue by Jonathaner** [kezong/fat-aar-android#42]
ERROR: Unable to resolve dependency for ':lib-main@debug/compileClasspath': Failed to transform artifact 'lib-aar.aar (project :lib-aar)' to match attributes {artifactType=jar}

大佬，我下载你的demo，example打开报错

**Comment by kezong** [comment]
是不是没有gradle wrapper？
我这里试了多次都没问题，你看看本地的配置环境是否有问题吧。

**Comment by kezong** [comment]
应该是网络原因，gradle plugin依赖没有下载下来。
