### ISSUE TITLE
Flavor support while specifying core dependency

### ISSUE THREAD

**Issue by mayankm786** [kezong/fat-aar-android#43]
My main aar has flavors and I would like to add dependencies based on which flavor is build.

Following gives an error

```
devEmbed 'com.facebook.fresco:fresco:1.11.0' 
``` 

Would it be possible to support this?

**Comment by kezong** [comment]
good issue, it doesn't support this now, but if I have time, I will add it.

**Comment by shily** [comment]
Waiting for this feature

**Comment by nillsondg** [comment]
Very necessary!

**Comment by kezong** [comment]
Plugin 1.2.12 is already supported.
