### ISSUE TITLE
★★★大佬，看下我的思路！！！急需自动化这个过程！！！★★★

### ISSUE THREAD

**Issue by chenenqiang12345** [kezong/fat-aar-android#44]
现在的问题是资源各种冲突，导致编译不成功，特别有很多依赖时！我可以提供一种思路，创建一个空application项目专门依赖各种library项目，build出apk，这里涵盖所有最终的依赖及资源（好处就是我们可以不需要考虑谷歌官方处理的过程，我们只需要拿到最终资源处理就行，重点是我们不需要自己处理，避免过程导致的各种问题，例如资源合并等），我们只要提取出有用的资源生成aar或者jar包，我觉得这是比较妥当的方法，因为这不需要你考虑工程结构及后期谷歌开发新功能导致的问题！目前我尝试了下这是可行的，现在的问题是我纯手动去改，比较麻烦，希望你能对过程直接实现自动化！这种好处可以做插件化！希望你能多抽时间处理下，我现在急需这个功能！

**Comment by kezong** [comment]
处理资源冲突的办法：
在gradle.properties中添加android.disableResourceValidation=true可以忽略资源冲突的编译错误，程序会采用第一个找到的同名资源作为实际资源，不过不建议这样做，如果资源同名但实际资源不一样会造成不可预期的问题。

application的编译方式也是采用第一个同名的资源作为实际资源。
