### ISSUE TITLE
请问是否可以支持远程jar和本地jar包，打包到aar的classes.jar里

### ISSUE THREAD

**Issue by BennyWang** [kezong/fat-aar-android#47]
目前来看，只有aar类型的依赖本身会被合并到宿主的classes.jar里边，早起的fat-aar gradle脚本是可以的，但是已经不维护了，不支持高版本的gradle

**Comment by kezong** [comment]
想问一下为什么想要一起打到claeese.jar里呢？

**Comment by BennyWang** [comment]
因为我们交付出去的其实是一个jar，不是aar，所以希望打到一起

**Comment by BennyWang** [comment]
对这块我不太熟悉，我clone了一份在本地做了修改并验证了，是可以的，但是我不知道打成一个classes.jar是不是有什么副作用？

**Comment by kezong** [comment]
你可以先本地改一改。
这个问题我先记一下，和混淆规则会有一定的冲突，有时间的话我看下。

**Comment by BennyWang** [comment]
好的，有个疑问，如果不打包到一起，混淆应该应用不到libs里边的jar吧，如果有需要一并混淆的话，就做不到了，是不是这样

**Comment by kezong** [comment]
是

**Comment by kezong** [comment]
试试1.2.5版本，需要开启minifyEnabled，最终才会打到一个jar包中，你可以选择全keep防止代码被混淆。
