### ISSUE TITLE
     public static int[] ActionMenuView = ***(自己的包名）.R.styleable.ActionMenuView;

### ISSUE THREAD

**Issue by hqglichao** [kezong/fat-aar-android#5]
/×××/build/intermediates/exploded-aar/r/com/***/R.java:2493: 错误: 找不到符号
    public static int[] ActionMenuView = ***(自己的包名).R.styleable.ActionMenuView;
                                                                                      ^
  符号:   变量 ActionMenuView
  位置: 类 styleable
1 个错误
这个是为啥?

**Comment by docwei2050** [comment]
我也遇到类似的问题了，多个library合并的话，一定要保证compile和build版本和support支持库版本一致，不然就会出现这种问题，，，这些都是系统的类找不到，系统版本不同，高版本下没有这些类了。java.lang.NoSuchFieldError: No field abc_action_bar_view_list_nav_layout of type I in class Lcom/example/mainlib/R$layout; or its superclasses (declaration of 'com.example.mainlib.R$layout' appears in /data/app/com.example.docwei.testtttttt-1/base.apk:classes2.dex)   我的问题，，，，，

**Comment by docwei2050** [comment]
其实多个aar合并，难点就是R文件映射，经常就是类找不到，哎

**Comment by kezong** [comment]
> 其实多个aar合并，难点就是R文件映射，经常就是类找不到，哎

现在还会出现R类找不到吗？

**Comment by jingyaxie** [comment]
> > 其实多个aar合并，难点就是R文件映射，经常就是类找不到，哎
> 
> 现在还会出现R类找不到吗？
还是会出现R类找不到

**Comment by docwei2050** [comment]
https://www.jianshu.com/p/8f7e32015836 这个博客提示可以禁用系统的支持库，不打到R文件里面

**Comment by SemonCat** [comment]
@docwei2050 

請問您可以提供不打包 Support 的版本參考下嗎？

**Comment by kezong** [comment]
> @docwei2050
> 
> 請問您可以提供不打包 Support 的版本參考下嗎？

不用embed, 使用compileOnly的话，dependency是不会被整体打包进aar的。
