### ISSUE TITLE
Remote dependencies of local dependencies not included

### ISSUE THREAD

**Issue by kassim** [kezong/fat-aar-android#50]
I add 
`configurations.embed.transitive = true` to my `:mainLib` `build.gradle`
and `embed ':localModule'`

but `:localModule` has a remote dependency
`implementation 'com.google.zxing:core:3.4.0'`
which isn't included in the final aar build

arguably it should be, right? 

I'm working around it by stating `embed 'com.google.zxing:core:3.4.0'` in my `:mainLib` `build.gradle` but seeing that ':localModule'` can actually be a dependency in a different repository (via git submodules, or in my case npm providing it for React Native) - I feel like this behaviour that I desire, makes sense to be part of this library

thank you for your work so far, it's been a very helpful tool!

**Comment by kassim** [comment]
actually... I think what could be also helpful, would be a way to produce a list of these remote dependencies, so that it can be distributed alongside the `.aar` as setup instructions

**Comment by kezong** [comment]
Yes, If you want to embed `:subModule`'s dependencies, you must be add `embed` these dependencies in your `:mainLib`
`transive = true` can only support remote dependencies under your `:mainLib` and invalid for local dependencies.
`embed` is now just a configuration item that determines which dependencies you need to bundle.(excluding multilevel dependencies)
However, multilevel dependencies and deeper dependencies are not well support now, so `embed` must be added to `:mainLib` to indicate them.

Analyzing dependencies between modules is one thing I want to do later, but it takes time.

**Comment by rasmussl** [comment]
Is support for `embed` for multilevel dependencies and deeper dependencies still something on the todo?
