### ISSUE TITLE
Execution failed for appcompat 28 references to other resources are not supported by build-time PNG generation. `configurations.embed.transitive = true`

### ISSUE THREAD

**Issue by mochadwi** [kezong/fat-aar-android#51]
@kezong 

Looks like when I'm activating `transitive` into `true`, show this error:

```
Execution failed for task ':app:packageReleaseResources'.
> Error: java.lang.RuntimeException: java.lang.RuntimeException: Error while processing /User/home/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/28.0.0/release/res/drawable/abc_ic_search_api_material.xml : Can't process attribute android:fillColor="@android:color/white": references to other resources are not supported by build-time PNG generation. See http://developer.android.com/tools/help/vector-asset-studio.html for details.
```

Does the problem related to this issue #15 and the cause for duplicated dependencies?

**Comment by kezong** [comment]
Please provide more information and error logs.

**Comment by mochadwi** [comment]
> Please provide more information and error logs.

What logs level you need @kezong ? 

so I can share the log output message

**Comment by kezong** [comment]
I think this is not a `fat-aar` bug.
Try add this in you `build.gradle`:
```groovy
android {
  defaultConfig {
    vectorDrawables.useSupportLibrary = true
  }
}
```

**Comment by mochadwi** [comment]
> I think this is not a `fat-aar` bug.
> Try add this in you `build.gradle`:
> 
> ```groovy
> android {
>   defaultConfig {
>     vectorDrawables.useSupportLibrary = true
>   }
> }
> ```

Nice, will check this later on. Thanks for the feedback @kezong
