### ISSUE TITLE
Android Gradle Plugin 3.5.0 Compatibility

### ISSUE THREAD

**Issue by llDavidll** [kezong/fat-aar-android#53]
Hi,

The latest Android Gradle plugin breaks the fat-aar plugin :

`Cannot expand ZIP '****\intermediates\compile_only_not_namespaced_r_class_jar\release\generateReleaseRFile\R.jar' as it does not exist.`

Path of the R.jar file with 3.4.2 :
`intermediates\compile_only_not_namespaced_r_class_jar\release\generateReleaseRFile\R.jar`
Path of the R.jar file with 3.5.0 :
`intermediates\compile_only_not_namespaced_r_class_jar\release\R.jar`

One step is really important : clean before trying to reproduce this error. Without a clean, old generated files are still present and are used by the plugin.

I think the fix should be made here by adding another case without the last part of the path (`/generate${mVariant.name.capitalize()}RFile`) :
https://github.com/kezong/fat-aar-android/blob/22e2a04fb419586ffd29a6b2beacee50d484b9f7/source/src/main/groovy/com/kezong/fataar/VersionAdapter.groovy#L36

I tried to build by manually puting the R.jar file in the old path and it seems to work, so it may be the only broken thing.

**Comment by llDavidll** [comment]
I have another issue linked to the new Android Gradle Plugin :

- Embed a dependency :
`embed 'your:dependency'`
Then build the project : the dependency is present in the aar.

- Remove the dependency completely or replace "embed" by "api":
`api 'your:dependency'`
Build the project again. The dependency should not be in the aar, but it is.

- Clean the project, rebuild : this time the dependency will not be in the aar.

This bug is only present in the 3.5.0.

**Comment by kezong** [comment]
Thanks for your issue, I will take time to look at this.

**Comment by krmao** [comment]
I am also find this bug about **classpath 'com.android.tools.build:gradle:3.5.0'**

**Comment by victorlaerte** [comment]
Also got this issue. Downgrade for 3.4.2 works until this is fixed.

**Comment by kezong** [comment]
I adapted 3.5.0 in fat-aar 1.2.6。
You can upgrade it.

**Comment by llDavidll** [comment]
Great, both issues have been fixed.  Thank you for your time !

**Comment by awushensky** [comment]
This issue has resurfaced with gradle `4.1.0`. Seems to work ok on `4.0.2`

**Comment by duanniston** [comment]
This issue has resurfaced with gradle 4.1.0. Seems to work ok on 4.0.2
