### ISSUE TITLE
Missing R file

### ISSUE THREAD

**Issue by zsweigart** [kezong/fat-aar-android#54]
When I build the fat aar, the r-classes.jar has R files for all embedded modules but not the main module

**Comment by kezong** [comment]
Main module's R.class will generate by application building with R.txt file.

**Comment by kezong** [comment]
@impvhc can you show me the main lib's `build.gradle`?

**Comment by kezong** [comment]
whose package name is `com.company.android.ui`?. 
Try the `compileOnly appcompat-v7` to `implementation appcompat-v7`
