### ISSUE TITLE
安卓自带包要如何处理？

### ISSUE THREAD

**Issue by kawais** [kezong/fat-aar-android#56]
安卓自带包要如何处理？像这些
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0'
如果用embed的话，会不会和应用aar的应用发生冲突？不用embed的话，又要在应用里面implementation一下，有点麻烦。

**Comment by kezong** [comment]
不建议embed，如果embed，必定会和application产生冲突。
只能使用`compileOnly`或者`implementation`的方式。

除非你上传maven仓库，生成pom文件。
