### ISSUE TITLE
打包后BuildConfig.class里面的内容是有错误

### ISSUE THREAD

**Issue by kawais** [kezong/fat-aar-android#57]
debug包里面的BuildConfig.class的内容是release的

这个是debug包的classes.jar反编译出来后的内容

public final class BuildConfig {
  public static final boolean DEBUG = false;
  
  public static final String APPLICATION_ID = "xxxxx";
  
  public static final String BUILD_TYPE = "release";
  
  public static final String FLAVOR = "";
  
  public static final int VERSION_CODE = 1;
  
  public static final String VERSION_NAME = "1.0";
}

**Comment by kawais** [comment]
debug包里面主module的BuildConfig.BUILD_TYPE是debug，但是子module的BUILD_TYPE都是release

**Comment by kezong** [comment]
这个编译是系统行为，应该是Google的bug，不用fat-aar编译出来也是release的，你可以google一下看是否有解决办法。

**Comment by kawais** [comment]
看到有方法说使用debugCompile project(path: ':library', configuration: 'debug')
但是我写成embed project(path: ':baselibrary', configuration:'debug')的话，sync会出错
Project :client declares a dependency from configuration 'embed' to configuration 'debug' which is not declared in the descriptor for project :baselibrary.

**Comment by kezong** [comment]
你可以试试implementation project(path: ':baselibrary', configuration:'debug') 官方的方式是否有用。

**Comment by zfl5232577** [comment]
implementation project(path: ':baselibrary', configuration:'debug') 能把其他module打包进去吗？

**Comment by kezong** [comment]
@zfl5232577  我拿官方implementation举例子，只是想说明加configuration:'debug'编译不过，不是加了embed的原因，是因为工程的配置问题。

implementation无法合并AAR。
