### ISSUE TITLE
Execution failed for task ':xxxxxx:createRsFilerelease'. > Cannot invoke method replace() on null object

### ISSUE THREAD

**Issue by wingyippp** [kezong/fat-aar-android#6]
dependencies {
    embed 'com.facebook.fresco:fresco:1.11.0'
    compileOnly 'com.facebook.fresco:fresco:1.11.0'
}

Set the dependencies above. Then it will build failed with the error log:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':xxxxxxx:createRsFilerelease'.
> Cannot invoke method replace() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

**Comment by kezong** [comment]
用的哪个版本？example工程也会报这个错吗？

**Comment by wingyippp** [comment]
哦是我工程的问题，打扰了

**Comment by zhoujian365** [comment]
> 哦是我工程的问题，打扰了

我遇到了一样的报错，请问你这边是怎么解决的？
