### ISSUE TITLE
在库工程使用fat-aar打包， 在assembleRelease的doLast，将合成的aar拷贝的主module中，总是出问题

### ISSUE THREAD

**Issue by huanting** [kezong/fat-aar-android#60]
问题：
    在Lib module中，使用fat-aar将各个aar打包成一个aar， 然后在打包完成时，拷贝到主module的libs目录。
问题：
    每次拷贝的文件，总是缺少r-classes.jar，
    是不是最好合成aar的时机比这个dolast还要晚，如果还要晚，应该在哪个时机去拷贝？

拷贝时机：
    assembleRelease的dolast， 具体如下：
tasks.all {
    if ("assembleRelease".equalsIgnoreCase(it.name)) {
        it.doLast({
            File srcFile = file("$projectDir/build/outputs/aar/total-release.aar")

            copy {
                from(srcFile.getAbsolutePath())
                into( rootProject.projectDir.getAbsolutePath() + "/app/libs/")
                rename {
                    "test-sdk-release-" + android.defaultConfig.versionName + ".aar"
                }
            }
        })
    }
}

**Comment by kezong** [comment]
你使用的哪个版本

**Comment by huanting** [comment]
版本：1.2.5

**Comment by kezong** [comment]
reBundleAarRelease应该是在assembleRelease之前才对，你可以打印一下Task的执行顺序看看。
