### ISSUE TITLE
合并so库出现的问题

### ISSUE THREAD

**Issue by bylijian** [kezong/fat-aar-android#61]
远程依赖的一个lib，包括v7a,v8a,x86的so库，本地的主library module只有v7a的库，它的build.gradle添加了过滤
ndk{
         abiFilters 'armeabi-v7a' 
      }
但是问题是，合并出来的aar包，过滤没有生效。aar包里面有v7a,v8a,x86文件夹，v7a里面有两个so，其他文件只有远程lib的so

**Comment by bylijian** [comment]
fat-aar能不能检测abiFilters 'armeabi-v7a' 这个，然后过滤掉别的so

**Comment by kezong** [comment]
abiFilter对library没有作用，建议在build.gradle中使用：
```groovy
android {

    ...

    packagingOptions {
        exclude 'lib/x86/*.so'
        exclude 'lib/x86_64/*.so'
        exclude 'lib/armeabi/*.so'
        exclude 'lib/arm64-v8a/*.so'
    }
}
```
