### ISSUE TITLE
请问报错Unable to load class com.android.build.gradle.api.LibraryVariant due to missing dependency org/gradle/api/tasks/TaskProvider 是什么问题

### ISSUE THREAD

**Issue by xiangmingzhe** [kezong/fat-aar-android#63]

**Comment by kezong** [comment]
gradle plugin和gradle的版本不匹配导致。
可以参考gradle官网建议的兼容版本。

**Comment by xiangmingzhe** [comment]
都是匹配的。。。。

**Comment by xiangmingzhe** [comment]
我是直接想运行下你这个自定义的gradle插件报这个错。。。。

**Comment by kezong** [comment]
你gradle和gradle plugin什么版本。
检查下是否在多个`build.gradle`中定义`com.android.tools.build:gradle:x.x.x`版本

**Comment by xiangmingzhe** [comment]
3.4.1和5.1.1
并没有存在对应多个版本

**Comment by xiangmingzhe** [comment]
我是直接想运行你的source项目。。。。然后就报这个错了

**Comment by kezong** [comment]
我这边没法复现，可以的话，可以发一个demo到我邮箱。
