### ISSUE TITLE
1.2.6 lib的AndroidManifest ${applicationId} 失效 

### ISSUE THREAD

**Issue by NicoToast** [kezong/fat-aar-android#65]
#23 问题和之前关掉的issues一样，1.2.5是正常的

**Comment by kezong** [comment]
麻烦提供下使用的gradle和gradle plugin版本

**Comment by NicoToast** [comment]
com.android.tools.build:gradle:3.5.0
gradle-5.4.1-all

**Comment by kezong** [comment]
应该是3.5.0版本在这一块做了些处理，我看一下。

**Comment by kezong** [comment]
@NicoToast 试试1.2.7版本

**Comment by NicoToast** [comment]
谢谢，可以了
