### ISSUE TITLE
合并 aar 后，xml 里面自定义 dataBinding 属性丢失问题

### ISSUE THREAD

**Issue by haoxunwang** [kezong/fat-aar-android#67]
使用1.2.7 fat-aar gradle plugin，合并多 module 后，发现 module 里面布局文件中的自定义 dataBinding 属性丢失造成编译失败，是对 data-binding 支持有问题吗？

(fig1-module 源文件)
![源文件](https://user-images.githubusercontent.com/10581642/65026759-c1f07480-d96b-11e9-9315-6b4969600c70.png)
(fig2-编译失败 log)
![error](https://user-images.githubusercontent.com/10581642/65026373-03cceb00-d96b-11e9-842b-c85dd8ecd9f4.png)

**Comment by haoxunwang** [comment]
sorry，这是db 造成的，有个编译错误，还以为是合成的问题...

**Comment by kezong** [comment]
目前是不支持合并data-binding的。

**Comment by haoxunwang** [comment]
有支持计划时间吗？

**Comment by kezong** [comment]
暂时没有

**Comment by kezong** [comment]
不过之前试过，如果只在主module中引入data-binding，应该没有什么问题。

**Comment by haoxunwang** [comment]
好的，多谢！回头也研究下 data-binding 原理，看能尝试支持下不 😄
