### ISSUE TITLE
打包aar，build/intermidiates/fat-R/其他lib包名文件夹/R.java报错

### ISSUE THREAD

**Issue by chaychan** [kezong/fat-aar-android#68]
里面那些值都是我最新模块的包名com.xxx.sdk的值，比如我其中一个模块的包名是com.xx.a，但是它的文件里面 int anim.push_bottom_in = com.xxx.sdk.R.anim.push_bottom_in，所以报错了，要如何解决呢

**Comment by kezong** [comment]
这个是正常的，报错是报错在lib编译时，还是app运行时？

**Comment by chaychan** [comment]
ib编译的时候，出现这个错整个task就终止了。

**Comment by kezong** [comment]
把报错的具体错误日志贴一下吧。
