### ISSUE TITLE
Failed to transform artifact 'lib1.aar (project :lib1)' to match attributes {artifactType=jar}

### ISSUE THREAD

**Issue by Sheng-Xuan** [kezong/fat-aar-android#69]
Hi, I have a project with 4 modules, I set one of them as the main module, the dependency relationship is main depends on lib1, and lib1 depends on lib2 and lib3. While I try to sync the project, I got error stated in the title. There are 6 errors:

Unable to resolve dependency for ':mainsdk@debug/compileClasspath':Failed to transform artifact 'lib1.aar (project :lib1)' to match attributes {artifactType=jar}
Unable to resolve dependency for ':mainsdk@debug/compileClasspath':Failed to transform artifact 'lib2.aar (project :lib2)' to match attributes {artifactType=jar}
Unable to resolve dependency for ':mainsdk@debug/compileClasspath':Failed to transform artifact 'lib3.aar (project :lib3)' to match attributes {artifactType=jar}

3 for @debug and 3 for @relase.

I added the dependency in mainsdk like this:

    embed project(path:':lib1', configuration:'default')
    embed project(path:':lib2', configuration:'default')
    embed project(path:':lib3', configuration:'default')

My gradle version 5.5.1
Gradle plugin version 3.4.2

Any clue of how to solve this?
Thanks

**Comment by Sheng-Xuan** [comment]
The other problem is do I need to add dependencies of child module in the way of 'embed'? Does the parent module needs to add all children's dependencies in its build.gradle file?

**Comment by kezong** [comment]
1.  Try clean the project.
2. The parent module needs to add all children's dependencies in its build.gradle file

**Comment by yurii-diachenko** [comment]
I have the same issue. Project clean didn't help.

**Comment by yurii-diachenko** [comment]
Alright, I finnally managed it to work. I had to do gradlew clean on entire project and the assemble an appropriate module to get final aar
