### ISSUE TITLE
上传maven时会缺失R文件

### ISSUE THREAD

**Issue by WindyChZh** [kezong/fat-aar-android#7]
使用maven将项目上传至maven时，到bundleReleaseAar就停止了，然后后续的R文件有确实

**Comment by kezong** [comment]
R文件是在assembleReleaseAar之后才会生成组装，你可以分两步来上传maven，第一步先assembleRelease生成aar，第二部再upload指定的aar到maven仓库。

**Comment by jeepc** [comment]
> R文件是在assembleReleaseAar之后才会生成组装，你可以分两步来上传maven，第一步先assembleRelease生成aar，第二部再upload指定的aar到maven仓库。

请问upload指定的aar到maven仓库要怎么实现，uploadArchives这个命令会重新生成aar的

**Comment by WindyChZh** [comment]
目前是先生成AAR,用mvn命令脚本上传到Maven,放弃使用gradle脚本了


 
---原始邮件---
发件人: "jeepc"<notifications@github.com>
发送时间: 2019年5月30日(星期四) 中午11:20
收件人: "kezong/fat-aar-android"<fat-aar-android@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"WindyChZh"<514900369@qq.com>;
主题: Re: [kezong/fat-aar-android] 上传maven时会确实R文件 (#7)


 
R文件是在assembleReleaseAar之后才会生成组装，你可以分两步来上传maven，第一步先assembleRelease生成aar，第二部再upload指定的aar到maven仓库。
  
请问upload指定的aar到maven仓库要怎么实现，uploadArchives这个命令会重新生成aar的

**Comment by kezong** [comment]
已在1.1.7版本中支持该功能，现在可以直接使用该插件publish到maven了。

**Comment by WindyChZh** [comment]
感谢！


 
---原始邮件---
发件人: "kezong"<notifications@github.com>
发送时间: 2019年6月4日(星期二) 中午11:03
收件人: "kezong/fat-aar-android"<fat-aar-android@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"WindyChZh"<514900369@qq.com>;
主题: Re: [kezong/fat-aar-android] 上传maven时会确实R文件 (#7)



已在1.1.7版本中支持该功能，现在可以直接使用该插件publish到maven了。
