### ISSUE TITLE
在app中包含plugin时报错

### ISSUE THREAD

**Issue by kawais** [kezong/fat-aar-android#70]
建了一个空项目，没有主lib，直接在app的build.gradle中加入
apply plugin: 'com.kezong.fat-aar'
提示 Failed to apply plugin [id 'com.kezong.fat-aar']
根build.gradle中已加入
classpath 'com.kezong:fat-aar:1.2.7'

![image](https://user-images.githubusercontent.com/8424926/65419953-6e31cf80-de32-11e9-96f6-f7a4fb315c81.png)

![image](https://user-images.githubusercontent.com/8424926/65419975-7ee24580-de32-11e9-8b2f-beb440e7495b.png)

**Comment by kezong** [comment]
1. 该插件只试用于library，无法在app中使用。
2. 你这个错误可能是网络问题，没下载下来。
