### ISSUE TITLE
ERROR: Can not find task bundleDebugAar!

### ISSUE THREAD

**Issue by lhs21** [kezong/fat-aar-android#71]
有看到issues有人提问该问题，按照它所提供的解决方法，尝试更新as gradle 的等到最新版本，即as 3.5   gradle  3.5.0    gradle-5.4.1-all.zip   仍然报错。
![$XB1~Z02L{U~ B) KQV)16I](https://user-images.githubusercontent.com/27982354/65566690-39369180-df86-11e9-9e1d-0b93502c8a19.png)

**Comment by lhs21** [comment]
想补充一点，就是我的工程在引用了一个aar，依赖了一个模块，如下图。只单纯   embed project(path: ':models', configuration:'default')没有报这个错，但是加上    embed project(path: ':aars', configuration:'default')。就会报该错误。。。。不知道为什么，是aars路径的问题吗。，，希望有空指点一下。多谢
![574ef5e0fcbee0b813aa47c50f83b7a](https://user-images.githubusercontent.com/27982354/65609426-58630c80-dfe2-11e9-88b2-fe1a704c1584.png)

**Comment by lhs21** [comment]
该问题已解决，不过是把这个pocketsphinx-android-5。。。。。.aar直接在app里新建了一个libs文件引用的。用另一个embed方法，这样就成功了

**Comment by kezong** [comment]
可以看一下你aars里的build.gradle内容，看看是否有引入其他的gradle plugin版本。

**Comment by lhs21** [comment]
哦哦哦哦哦哦哦，有可能，，不过我没有aars的源程序，以后如果再遇到可以尝试一下，还是谢谢您抽空回复我啦
