### ISSUE TITLE
Not working if run sample project from Android Studio

### ISSUE THREAD

**Issue by askarsyzdykov** [kezong/fat-aar-android#72]
Hi, I use the plugin for building fat-aar in a project with Flutter dependency. The plugin works if I build aar via `./gradlew assemble`.

But if I run app from Android Studio, using `embed project(path: ":flutter", configuration: "default")`, I got runtime exception:
> Caused by: java.lang.ClassNotFoundException: Didn't find class "io.flutter.app.FlutterActivity" on path: DexPathList[[zip file "/data/app/kz.app.sample-igtLJceSY37ZFl4Zn1WPuQ==/base.apk"],nativeLibraryDirectories=[/data/app/kz.btsdigital.sample-igtLJceSY37ZFl4Zn1WPuQ==/lib/arm64, /data/app/kz.btsdigital.sample-igtLJceSY37ZFl4Zn1WPuQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]

But if I revert to `implementation project(":flutter")`, it works in Android Studio and doesn't work if I build aar.

Could you help me, plz?

I have a project https://github.com/askarsyzdykov/native_flutter_lib/. Build.gradle -- https://github.com/askarsyzdykov/native_flutter_lib/blob/master/library/build.gradle

**Comment by kezong** [comment]
Not only do you need to add `embed project(":flutter")`, but also to add `embed` to flutter module's dependencies as well.

It is recommended that AAR be compiled by fat-aar before application building, then you can add `implementation project("embeded-aar")` to your application.
