### ISSUE TITLE
打包后的的aar，提示Found item Attr/** more than one time

### ISSUE THREAD

**Issue by yunxingyu** [kezong/fat-aar-android#73]

**Comment by kezong** [comment]
请提供更多的信息，看看lib里是否有资源冲突。

**Comment by xuqinchun** [comment]
i have the same issue

**Comment by wolongalick** [comment]
> Task :ModuleB:packageReleaseResources FAILED
AGPBI: {"kind":"error","text":"Found item Attr/icon more than one time","sources":[{"file":"D:\\studio_workspace\\SiHuo\\FatAarApp\\ModuleB\\build\\intermediates\\exploded-aar\\FatAarApp\\ModuleC\\unspecified\\release\\res\\values\\values.xml"}],"tool":"Resource and asset merger"}
AGPBI: {"kind":"error","text":"Found item Attr/icon more than one time","sources":[{"file":"D:\\studio_workspace\\SiHuo\\FatAarApp\\ModuleB\\build\\intermediates\\exploded-aar\\FatAarApp\\ModuleC\\unspecified\\release\\res\\values\\values.xml"}],"tool":"Resource and asset merger"}

Execution failed for task ':ModuleB:packageReleaseResources'.
> D:\studio_workspace\SiHuo\FatAarApp\ModuleB\build\intermediates\exploded-aar\FatAarApp\ModuleC\unspecified\release\res\values\values.xml: Error: Found item Attr/icon more than one time

**Comment by wolongalick** [comment]
I give up

**Comment by MoonBlueSky** [comment]
这个问题好像是导入'androidx.appcompat:appcompat:1.2.0'和'androidx.core:core:1.2.0'会出现，或者是其他拥有相同attr属性没有经过判断就被合并起来，最后就是会提示有多个declare-styleable中重复的声明了同一个attr，需要把它手动提取attr出来进行复用，但是很多库会有这种重复
例如：'com.google.android.material:material:1.2.1'和'androidx.appcompat:appcompat:1.2.0'中
都存在了<attr format="color" name="backgroundTint"/>
他们分别位于
<declare-styleable name="Tooltip">和    <declare-styleable name="ViewBackgroundHelper">中
正常处理应该修改这两者中的<attr format="color" name="backgroundTint"/>为<attr name="backgroundTint"/>
然后再定义一个公用的<attr format="color" name="backgroundTint"/>
就可以解决这个冲突，这一部分需要进行修复，gradle编译时不存在该问题，应该是有进行了此步操作 @kezong

**Comment by MoonBlueSky** [comment]
这个问题好像是导入'androidx.appcompat:appcompat:1.2.0'和'androidx.core:core:1.2.0'会出现，或者是其他拥有相同attr属性没有经过判断就被合并起来，最后就是会提示有多个declare-styleable中重复的声明了同一个attr，需要把它手动提取attr出来进行复用，但是很多库会有这种重复
例如：'com.google.android.material:material:1.2.1'和'androidx.appcompat:appcompat:1.2.0'中
都存在了
`<attr format="color" name="backgroundTint"/>`
他们分别位于
`<declare-styleable name="Tooltip">`和 `<declare-styleable name="ViewBackgroundHelper">`中
正常处理应该修改这两者中的为 `<attr name="backgroundTint"/>`
然后再定义一个公用的 `<attr format="color" name="backgroundTint"/>`
就可以解决这个冲突，这一部分需要进行修复，gradle编译时不存在该问题，应该是有进行了此步操作 @kezong
