### ISSUE TITLE
I want to include an annotation processor module into my fat AAR, how?

### ISSUE THREAD

**Issue by gefilte** [kezong/fat-aar-android#74]
I can't "embed" my annotation processor module,  because of compile behavior, etc. But I want to include the module as a lib (JAR) in my fat AAR. Is there some way to do this with the current system? Or is a change needed to support this.

**Comment by kezong** [comment]
Can you provide more detail log?

**Comment by gefilte** [comment]
Sure. My component has 3 modules: the main android library (for publishing) "core-sdk", a java library "core-sdk-annotations" with annotation classes, and a java library "core-sdk-annotation-processor" with an annotation processor class. They all need to be used together, but the annotation processor doesn't even get used by the main library: it's intended to be used by whomever is including the library. As such, it's only included in the tests for "core-sdk".

Without caring about publishing, the java libraries are included in the main android library like:
```
    compileOnly project(':core-sdk-annotations')
    testCompileOnly project(':core-sdk-annotations')
    kaptTest deps.auto_service
    kaptTest project(':core-sdk-annotation-processor')
```

If I add:
```
    embed project(path: ':core-sdk-annotations')
```
this works fine: I see the AAR build product contains a `libs` dir with `core-sdk-annotations.jar`.
If however I add
```
    embed project(path: ':core-sdk-annotation-processor')
```
The compiler will complain:
```
Execution failed for task ':core-sdk:javaPreCompileDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
       - core-sdk-annotation-processor.jar (project :core-sdk-annotation-processor)
     Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
     See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.
```

If I follow the suggestion of this error message and add `android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true` to my `build.gradle`, this happens:
```
* What went wrong:
Execution failed for task ':core-sdk:compileDebugJavaWithJavac'.
> com/squareup/kotlinpoet/TypeName
```

Running with `--debug` or `--stacktrace` revealed no interesting details about what is wrong, just what you would expect:
```
Caused by: java.lang.NoClassDefFoundError: com/squareup/kotlinpoet/TypeName
...
Caused by: java.lang.ClassNotFoundException: com.squareup.kotlinpoet.TypeName
```

`kotlinpoet` is a library used by the annotation processor. It's irrelevant to the build task `:core-sdk:compileDebugJavaWithJavac`, but because of how `embed` works, it tries to use it.

So what I want to do, is somehow embed the the "core-sdk-annotation-processor" JAR into my "core-sdk" AAR so clients won't need to load it as a separate dependency. Not sure it is possible though.

**Comment by kezong** [comment]
`embed` is not transitive.
You must add embed for transitive dependencies in your core-sdk library.

For example, `core-sdk` depend on `core-sdk-annotation-processor`, `core-sdk-annotation-processor` depend on `kotlinpoet`, If you want including all dependencies in final artifact, you must add embed for `core-sdk-annotation-processor` and `kotlinpoet` in`core-sdk` build.gradle

**Comment by gefilte** [comment]
But `kotlinpoet` isn't my code, it's a library I don't want to embed because it's a published library.

**Comment by kezong** [comment]
Will there be build success when you change `embed` to `implementation`? like this:
```groovy
implementation project(path: ':core-sdk-annotation-processor')
```

**Comment by kezong** [comment]
The plugin does not support replacing `kapt` with `embed` directly, but only `compileOnly` and `implementation`. 
`embed` is compiled by `compileOnly`.
