### ISSUE TITLE
把多个moudle打成一个aar，打包可以成功，运行奔溃，报support:appcompat/res/layout下的资源找不到。

### ISSUE THREAD

**Issue by docwei2050** [kezong/fat-aar-android#75]
支持库的版本不同，layout目录下的res会有所不同，
比如：abc_action_bar_view_list_nav_layout 找不到 （27/28版本没有这个，26以及低版本是有的）
     abc_cascading_menu_item_layout 找不到  （27/26没有，28是有的）

输出aar的时候，就算强制指定所有project的support库的版本为28.0.0，输出的aar还是会受到libs目录下的aar或者第三方在线依赖的aar影响，就算这些aar不打进我们的要输出的aar，只要他们参与编译了，它们的R.txt（aar后缀改成zip解压，查看R.txt）里面含有26或者低版本才有的res文件名，那么我们输出的aar的R.txt就一定含有26或者低版本的这个res文件名，
在运行的时候就报找不到。

java.lang.NoSuchFieldError: No field abc_action_bar_view_list_nav_layout of type I in class Lcom/example/mainlib/R$layout; or its superclasses (declaration of 'com.example.mainlib.R$layout' appears in /data/app/com.example.docwei.testtttttt-1/base.apk:classes2.dex)

宿主接入的时候，他们如果支持库是28.0.0，编译就报26或者低版本才有的 abc_action_bar_view_list_nav_layout 找不到奔溃，宿主同时加上26.0.2的支持库，重复类的冲突就出现了。

**Comment by kezong** [comment]
在library中引用support的时候，使用`comileOnly`试试，这样就不会生成不需要的R.txt，不要使用`implementation`

**Comment by hf529270451** [comment]
请问楼主解决这个问题了吗

**Comment by ChenKunFeng** [comment]
改成comileOnly，会报     AAPT: error: resource style/Theme.AppCompat.Dialog (aka com.ztesoft.baselib:style/Theme.AppCompat.Dialog) not found.

**Comment by docwei2050** [comment]
解决了哦

**Comment by kezong** [comment]
升级到最新版本，应该能解决问题。
