### ISSUE TITLE
样例example报错

### ISSUE THREAD

**Issue by wenfengtou** [kezong/fat-aar-android#76]
ERROR: Unable to resolve dependency for ':lib-main@debug/compileClasspath': Failed to transform artifact 'lib-aar.aar (project :lib-aar)' to match attributes {artifactType=jar}.
Show Details
Affected Modules: lib-main

配置是：
com.android.tools.build:gradle:3.5.0
gradle版本：5.4.1

**Comment by wenfengtou** [comment]
com.android.tools.build:gradle:3.4.2 是ok的

**Comment by kezong** [comment]
./gradlew clean一下
