### ISSUE TITLE
大小写不同但字母相同的两个class文件，打包后其中之一丢失

### ISSUE THREAD

**Issue by bu1l3t** [kezong/fat-aar-android#77]
使用第三方aar生成aar的工程：
比如有一sdk.aar，里面的classes.jar有 Ab.class和ab.class两个文件，但fat-aar生成的新aar中，只会存在Ab.class，ab.class不见了。

**Comment by kezong** [comment]
这个大小写敏感问题，可能没有太好的解决办法，建议在混淆时加入-dontusemixedcaseclassnames，避免出现Ab和ab同时出现。
