### ISSUE TITLE
WARNING: API 'variantOutput.getPackageLibrary()' is obsolete

### ISSUE THREAD

**Issue by LePengTian** [kezong/fat-aar-android#78]
WARNING: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

**Comment by kezong** [comment]
I didn't call this interface directly, this a system call that I couldn't fix it, I think Google should fix it later.

**Comment by LePengTian** [comment]
OK THX dude
