### ISSUE TITLE
集成生成后的aar文件，在主module调用时出现找不到aar文件里面的静态常量和方法

### ISSUE THREAD

**Issue by jackom** [kezong/fat-aar-android#79]
作者你好！
    我目前在gradle-4.10.1-all 、com.android.tools.build:gradle:3.3.2、 as版本 3.5.1 上集成了你的开源库，目前有一个主module和子lib module，在主module的libs中加入了子 lib module编译后生成的aar文件，然后再在主module的build.gradle里面通过：implementation(name: XXX, ext: 'aar')方法依赖进去。
  
  子 lib mudule里面的结构如下：
  dependencies {
	implementation fileTree(include: ['*.jar'], dir: 'libs')
	compileOnly rootProject.ext.dependencies["xutils"]
	compileOnly rootProject.ext.dependencies["eventbus"]
	compileOnly rootProject.ext.dependencies["support-v4"]
	embed files('libs/classes.jar')

	compileOnly rootProject.ext.dependencies["appcompat-v7"]

	//依赖A
	embed(name: 'aa1', ext: 'aar')
	embed(name: 'aa2', ext: 'aar')
	embed(name: 'aa3', ext: 'aar')
	embed(name: 'aa4', ext: 'aar')
	embed(name: 'aa5', ext: 'aar')
	embed(name: 'aa6', ext: 'aar')
	embed(name: 'aa7', ext: 'aar')

	//依赖B
	embed(name: 'bb', ext: 'aar')
	implementation 'pl.droidsonroids.gif:android-gif-drawable:1.2.6'

	//依赖C
	embed files('libs/cc.jar')
	implementation 'com.squareup.picasso:picasso:2.5.2'

}

   在把子lib module编译生成的aar文件(因为assembleRelease的过程中报错了，编译失败，所以我在混淆代码里面加了：-ignorewarnings)集成到主module后，我直接rebuild project，然后报错了，**报错的地方提示主module中的OneActivity找不到子lib module的TwoActivity中定义的静态常量和C方法(方法都是public的)**(其中，主module中的TwoActivity继承了子lib module的BaseActivity，该子libmodule的BaseActivity继承了子lib module的TwoActivity)。
   

   **其中，我在主module中，通过代码跳转进入到 子lib module的TwoActivity，发现该类中定义的跟 依赖A、B、C相关的代码都不见了，保留下来的只是跟依赖A、B、C无关的代码**
   
   
   **备注：我如果不将子lib module编译成aar文件再集成到主module里面，而是采取直接在 主module的build.gradle中通过 implementation project(path: ':子lib module名称') 方式依赖，就不会有上面提到的 代码丢失导致静态变量跟方法 找不到的问题。**
   
   最后希望能帮忙看下，帮忙解决下。因为子lib module是要当做sdk提供给别人集成，并不是在自己项目里面使用，所以最终还是要生成aar文件。

**Comment by kezong** [comment]
你试试assembleDebug是不是可以正常运行，也可以逆向看下生成后的aar中的class文件，感觉像是被混淆了。

**Comment by jackom** [comment]
> 你试试编译子lib的aar时用assembleDebug是不是可以正常运行，也可以逆向看下生成后的aar中的class文件，感觉像是被混淆了。

我是直接assembleRelease编译子lib的module文件的，另外发现，打包出来的debug包体积比release包还要小，我解压缩debug包的aar文件，发现里面并没有把aar集成进去，但是release包的aar文件里面是有的，但是存在 上面提到的 子lib的module中Activity里面 剔除了 子lib module依赖的其他aar文件。。

**Comment by kezong** [comment]
debug和release机制不一样，你解压aar文件用什么方法查看是否aar有被集成？

**Comment by jackom** [comment]
我是把aar文件重命名为zip文件，然后直接解压缩，看里面的代码没有包含 被依赖的aar文件的包名。

**Comment by kezong** [comment]
你使用的fat-aar是哪个版本？
debug包，因为不用混淆，所以部分依赖是libs/目录下，
 release包会将所有class合并至classes.jar中。
你可以再review一下。

从你这种现象应该是类被混淆了，你都keep住试试。

**Comment by jackom** [comment]
我用的是最新的1.2.7版本的。我现在已经在子lib的module里面加入了被依赖的第三方aar的混淆了的。

**Comment by jackom** [comment]
![从主module代码跳转进入的子lib里面的Activity类](https://user-images.githubusercontent.com/5052960/66807132-5f36cc80-ef5b-11e9-8dd7-db1d3f5383b9.png)

![子lib里面的Activity类](https://user-images.githubusercontent.com/5052960/66807165-62ca5380-ef5b-11e9-8c7b-9f02575e1358.png)

![子lib的编译方式](https://user-images.githubusercontent.com/5052960/66807140-5fcf6300-ef5b-11e9-9a1a-1a599be4874a.png)

**Comment by jackom** [comment]
> 你使用的fat-aar是哪个版本？
> �debug包，因为不用混淆，所以部分依赖是libs/目录下，
> release包会将所有class合并至classes.jar中。
> 你可以再review一下。
> 
> 从你这种现象应该是类被混淆了，你都keep住试试。

这个提到的类被混淆了，这里具体是指被依赖的第三方aar里面的类吗？混淆配置那里我有配置Activity不被混淆的，另外混淆配置里面也有加入 第三方的aar文件它们提供的混淆代码

**Comment by kezong** [comment]
你AdvertBaseActivity没有被调用的方法被proguard过滤了，你keep怎么加的，发来看看？

**Comment by jackom** [comment]
我的AdvertBaseActivity没有被调用的方法我没有加keep的，我的混淆配置里面也只是一般的设置不混淆Activity.

#---------------------------------基本指令区----------------------------------
-optimizationpasses 5
-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-dontskipnonpubliclibraryclassmembers
-dontpreverify
-verbose
-printmapping proguardMapping.txt
-optimizations !code/simplification/cast,!field/*,!class/merging/*
-keepattributes *Annotation*,InnerClasses
-keepattributes Signature
-keepattributes SourceFile,LineNumberTable
#----------------------------------------------------------------------------

#---------------------------------默认保留区---------------------------------
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.app.backup.BackupAgentHelper
-keep public class * extends android.preference.Preference
-keep public class * extends android.view.View
-keep public class com.android.vending.licensing.ILicensingService
-keep class android.support.** {*;}

#忽略所有警告(推荐不要使用，这会有很大的风险)
-ignorewarnings

-keepclasseswithmembernames class * {
    native <methods>;
}
-keepclassmembers class * extends android.app.Activity{
    public void *(android.view.View);
}
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
-keep public class * extends android.view.View{
    *** get*();
    void set*(***);
    public <init>(android.content.Context);
    public <init>(android.content.Context, android.util.AttributeSet);
    public <init>(android.content.Context, android.util.AttributeSet, int);
}
-keepclasseswithmembers class * {
    public <init>(android.content.Context, android.util.AttributeSet);
    public <init>(android.content.Context, android.util.AttributeSet, int);
}
-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}
-keep class **.R$* {
 *;
}
-keepclassmembers class * {
    void *(**On*Event);
}
#----------------------------------------------------------------------------

#---------------------------------webview------------------------------------
-keepclassmembers class fqcn.of.javascript.interface.for.Webview {
   public *;
}
-keepclassmembers class * extends android.webkit.WebViewClient {
    public void *(android.webkit.WebView, java.lang.String, android.graphics.Bitmap);
    public boolean *(android.webkit.WebView, java.lang.String);
}
-keepclassmembers class * extends android.webkit.WebViewClient {
    public void *(android.webkit.WebView, jav.lang.String);
}


这个是我这边基本的混淆配置，然后 第三方的混淆是按照它们提供的混淆方式添加到同一文件下面的，我这边暂时不粘贴出来了。

**Comment by jackom** [comment]
> 你AdvertBaseActivity没有被调用的方法被proguard过滤了，你keep怎么加的，发来看看？

另外你的意思是说还要针对  AdvertBaseActivity类中被proguard过滤导致没有被调用的方法 进行keep操作吗？

**Comment by kezong** [comment]
如果是对外类或者方法，是都需要keep的，不然编译时发现没被调用都会被proguard。
你全keep住试试：
```
#-keep class 包名 { *; }
```

**Comment by jackom** [comment]
> 如果是对外类或者方法，是都需要keep的，不然编译时发现没被调用都会被proguard。
> 你全keep住试试：
> 
> ```
> #-keep class 包名 { *; }
> ```

好的，我再试试。

**Comment by kezong** [comment]
@jackom 应该是`#-keep class 包名.** { *; }`

**Comment by jackom** [comment]
> @jackom 应该是`#-keep class 包名.** { *; }`

现在是能找到方法了，谢谢大佬耐心解答！我最后用的是： -keep class 包名.** { *; }  前面没有 '#' 符号。

**Comment by jackom** [comment]
另外，打debug包的时候，可以也把被依赖的aar里面的jar包都合并到最终的classes.jar包里面吗？因为加了混淆后，有时候比较难排查问题。特别是第三方的aar

**Comment by kezong** [comment]
不加在classes.jar里，也可以使用吧，都是一个aar中的。

**Comment by jackom** [comment]
> 不加在classes.jar里，也可以使用吧，都是一个aar中的。

不是阿，因为debug方式打包出来的aar文件没有包含第三方的aar(刚才你提到的：debug包，因为不用混淆，所以部分依赖是libs/目录下)，我现在是想打包出来一个能包含第三方aar的融合后的aar文件，然后集成使用。  另外，刚才的方式keep住包名下的所有代码，那样总感觉不安全阿，不过不keep住，又找不到类中的某些方法。。。

**Comment by kezong** [comment]
包含了啊，第三方的aar中的jar在libs/目录下，也属于整体的aar内。

**Comment by jackom** [comment]
> 包含了啊，第三方的aar中的jar在libs/目录下，也属于整体的aar内。

我打包出来的debug包里面没找到阿，但是release包里面的aar文件是包含了第三方的aar文件。。

**Comment by kezong** [comment]
你单独编译assembleDebug试试，你先别看里面是否少了文件，你直接拿debug包放在主module里面运行，看看会不会出错，报什么错。

**Comment by jackom** [comment]
> 你单独编译assembleDebug试试，你先别看里面是否少了文件，你直接拿debug包放在主module里面运行，看看会不会出错，报什么错。

我刚刚试了，把debug包里面的aar A添加到主module上，查看 as里面的 External Libraries，里面的aar A文件中也会包含 被依赖的第三方的aar文件，这个感觉有些奇怪的(主要还是因为debug包里面的aar文件体积比release包里面的aar文件还要小)。   另外还发现另外一个问题：就是我的子lib module里面，如果在libs目录下存放名字为 classes.jar 的文件B，那么在融合为一个aar之后，该aar里面会找不到 前面所提到的 B文件中的类(debug包的情况下)

**Comment by kezong** [comment]
关于子lib中引入libs目录下jar包的问题，你可以试试仓库中的[example](https://github.com/kezong/fat-aar-android/tree/master/example)，也有这种引入jar包的case。
debug的情况下libs下的jar包会生成在aar中的libs/目录下。

如果你确定aar中libs/目录下没有的话，可以尝试在[example](https://github.com/kezong/fat-aar-android/tree/master/example)中复现，然后告诉我复现步骤。

**Comment by jackom** [comment]
好的，我找时间测试下。

**Comment by jackom** [comment]
你好，我这边重现了昨天提到的问题，在TestJars项目中的README.md文件中也大致说了下自己的猜测，另外 TestJars项目和example项目里面都附有截图。 希望抽空帮忙看下。我是用assemble打包，然后依赖debug目录中的aar文件。

[example.zip](https://github.com/kezong/fat-aar-android/files/3732651/example.zip)
[TestJars.zip](https://github.com/kezong/fat-aar-android/files/3732652/TestJars.zip)
