### ISSUE TITLE
I keep getting folowing error "No signature of method: org.gradle.api.internal.artifacts.DefaultResolvedArtifact.getBuildDependencies() is applicable for argument types: () values: []"

### ISSUE THREAD

**Issue by olenasol** [kezong/fat-aar-android#8]
I get this error after adding plagin and trying to embed some external projects.
gradle version 3.2.1
ansroid studio version - 3.4

**Comment by kezong** [comment]
See if there are multiple build.gradle files that declare the version of com.android.tools.build:gradle, resulting in a version that is not 3.2.1.

What is the version of gradle wrapper using when you building?

**Comment by kezong** [comment]
Fix in version 1.1.6, You can try it.

**Comment by huaxiaos** [comment]
classpath 'com.kezong:fat-aar:1.2.18'

has the same issue
