### ISSUE TITLE
Failed to transform artifact 'room.aar (project :room)' to match attributes {artifactType=jar}

### ISSUE THREAD

**Issue by AnD010** [kezong/fat-aar-android#82]
Hi, 
I have a problem when making a  fat AAR  with 
gradle 3.5.1 but , but with 3.5.0 and 3.4.2 failed too. compileSdkVersion 29
targetSdkVersion 29 
Android Studio 3.5
Build #AI-191.8026.42.35.5791312, built on August 9, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15

Two weeks ago work fine when only have 1 
embed project(path: ':dsnetworking', configuration:'default')
I try many times ./gradlew clean and now  nothing work... I remove idea folder....but still not working...
this is the error
ERROR: Unable to resolve dependency for ':dscore@debug/compileClasspath': Failed to transform artifact 'networking.aar (project :dsnetworking)' to match attributes {artifactType=jar}.
Show Details
Affected Modules: dscore
ERROR: Unable to resolve dependency for ':dscore@debug/compileClasspath': Failed to transform artifact 'dsroom.aar (project :dsroom)' to match attributes {artifactType=jar}.
Show Details
Affected Modules: dscore

ERROR: Unable to resolve dependency for ':dscore@release/compileClasspath': Failed to transform artifact 'dsnetworking.aar (project :dsnetworking)' to match attributes {artifactType=jar}.
Show Details
Affected Modules: dscore

ERROR: Unable to resolve dependency for ':dscore@release/compileClasspath': Failed to transform artifact 'dsroom.aar (project :dsroom)' to match attributes {artifactType=jar}.
Show Details
Affected Modules: dscore

This is the gradle of my main lib

> apply plugin: 'com.android.library'
> apply plugin: 'kotlin-android'
> apply plugin: 'kotlin-android-extensions'
> apply plugin: 'com.kezong.fat-aar'
> 
> repositories {
>     flatDir {
>         dirs 'libs'
>     }
> }
> 
> android {
>     compileSdkVersion 29
>     buildToolsVersion "29.0.1"
> 
> 
>     defaultConfig {
>         minSdkVersion 21
>         targetSdkVersion 29
>         versionCode 1
>         versionName "1.0"
> 
>         testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
>         consumerProguardFiles 'consumer-rules.pro'
>     }
> 
>     buildTypes {
>         release {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
>         }
>     }
> 
> }
> 
> dependencies {
>     implementation fileTree(dir: 'libs', include: ['*.jar'])
>     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
>     implementation 'androidx.appcompat:appcompat:1.1.0'
>     implementation 'androidx.core:core-ktx:1.1.0'
> 
>     embed project(path: ':dsnetworking', configuration:'default')
>     embed project(path: ':dsroom', configuration:'default')
> 
> 
> 
>     testImplementation 'junit:junit:4.12'
>     androidTestImplementation 'androidx.test:runner:1.2.0'
>     androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
> }

Thanks so much

**Comment by kezong** [comment]
try to clean the project

**Comment by usman-ghani127** [comment]
delete the `react-native` from `node_modules` and run `yarn` again.
