### ISSUE TITLE
子包依赖的aar如何打包？

### ISSUE THREAD

**Issue by kawais** [kezong/fat-aar-android#83]
比如主lib依赖lib1，lib1依赖一个本地的aar文件，位于lib1/libs下。
主lib和lib1的build.gradle该如何写可以将aar打包到最终文件中？

**Comment by kawais** [comment]
我的主lib依赖2个子包lib1和lib2，
lib1依赖2个aar文件，build.gradle
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation fileTree(dir: 'libs', include: ['*.aar'])

lib2依赖1个jar文件，build.gradle
    implementation fileTree(dir: 'libs', include: ['*.jar'])

最终的debug包中的libs只有lib2的jar文件，没有lib1的aar文件

**Comment by kezong** [comment]
不管是主lib还是子lib依赖的aar文件，都需要用embed在主lib中引用，才能最终合入产物中。

**Comment by kawais** [comment]
那就是我还要把aar复制一份到主lib中才能完成打包？

**Comment by kezong** [comment]
不用复制，可以使用flarDir的方式引用本地aar，也可以将本地aar构成一个module供多方引入。

**Comment by kawais** [comment]
flarDir怎么引用别的模块下的aar?

**Comment by SugerQ** [comment]
解决了么？？我也有这个问题，能否指教一二

**Comment by guominfang** [comment]
@kawais @SugerQ 
可以在主的Lib中的gradle文件中添加
```
repositories {
    flatDir {
        // 添加其他module相对主LibModule的相对路径
        dirs 'libs', '../otherModuleName/libs'
    }
}

dependencies {
    embed(name: 'miit_mdid_1.0.10', ext: 'aar')
}
```

**Comment by 365720084** [comment]
这样打出来的aar只有依赖的aar的R文件诶，其他代码没有打起来

**Comment by initialjie** [comment]
> @kawais @SugerQ
> 可以在主的Lib中的gradle文件中添加
> 
> ```
> repositories {
>     flatDir {
>         // 添加其他module相对主LibModule的相对路径
>         dirs 'libs', '../otherModuleName/libs'
>     }
> }
> 
> dependencies {
>     embed(name: 'locatAARName', ext: 'aar')
> }
> ```

但是这样搞，就有点麻烦和不够灵活了，项目模块众多，难道都要在这写一遍吗？万一后面有增添删除，维护感觉很麻烦
