### ISSUE TITLE
同时引入com.android.support:design、appcompact报资源冲突，该如何解决呢

### ISSUE THREAD

**Issue by zxxyyxf** [kezong/fat-aar-android#85]
[attr/closeIcon] F:\OWS\OWSReconsituation\frame_work_3rd_library\build\intermediates\exploded-aar\com.android.support\design\28.0.0\release\res\values\values.xml	[attr/closeIcon] F:\OWS\OWSReconsituation\frame_work_3rd_library\build\intermediates\exploded-aar\com.android.support\appcompat-v7\28.0.0\release\res\values\values.xml: Error: Duplicate resources

**Comment by kezong** [comment]
请参考#22
