### ISSUE TITLE
问题反馈：混淆的逻辑有问题？混淆下的子module的R类的处理时机问题？

### ISSUE THREAD

**Issue by docwei2050** [kezong/fat-aar-android#86]
1.目前我们将多个module打成一个aar编译运行成功了。
实现：主module是一个空壳，embeded了多个子module，每一个子 module都不混淆，在主module下设置混淆，然后一定要把子module的混淆规则全部copy到主module的混淆文件里。（看源码其实是做了这个操作的，但是貌似没用，还得自己手动去添加到主module的proguard-rules.pro里。）

2.混淆模式下，编译出现会出现R类找不到。xx can't find referenced class xx.xxx.R
  实际上源码有处理将各个子embeded的R类打包到最终生成的aar文件libs目录下（r-class.jar）
  要想编译生成aar必须加 -ignorewarnings，这样输出的aar最终也是可以正常运行的。
 但是有强迫症的人看到红色的warning就想处理，麻烦作者处理下R类生成的时机，感觉生成R类的时机晚了，导致前面编译的时候，提示这个报错。

**Comment by kezong** [comment]
感谢提问，这两个都是已知问题。
1：这个proguard合并目前来说确实是有问题的，需要手动将proguard文件拷贝到主lib下，因为最近太忙，而又可以手动干预，所以我暂时没有修复该问题，有时间的话我会继续跟进。

2：R类生成的时机我找了很久，如果过早生成的话，在编译时系统会自动将你生成的给删掉，目前为止我还没有找到系统删除R文件的相关资料，所以只能将生成的代码放在bundle之后，如果你有这方面的资料也欢迎提供给我。

**Comment by liujingg** [comment]
同样遇到dontusemixedcaseclassnames不生效的问题，这个问题还挺困扰的
