### ISSUE TITLE
Compiling all dependencies in debug mode

### ISSUE THREAD

**Issue by askarsyzdykov** [kezong/fat-aar-android#87]
Hi, @kezong 

Does the plugin use debug mode if I run `./gradlew assembleDebug` for all dependencies?
Why I'm asking - my_library-release.aar contains dependencies that has `BuildConfig.DEBUG = false`. I assume that the far-aar plugin uses release aars instead of debug.

On the right side of the picture placed my library and its debug = true (correct), on the left side - dependency of my library and its debug=false (incorrect). 
![image](https://user-images.githubusercontent.com/3222305/67853384-a666b500-fb38-11e9-850f-283ac8556b74.png)

p.s: The dependency's `build` folder contains both release and debug file
![image](https://user-images.githubusercontent.com/3222305/67853611-212fd000-fb39-11e9-8394-769bdcad0a48.png)

I don't known maybe I'm wrong, but I don't know any reason what it happens

**Comment by kezong** [comment]
This is Google's behavior.
If you use 'implementation' replace `embed`, it will be the same. 
It is recommended to search online for solutions.

**Comment by askarsyzdykov** [comment]
@kezong Hi, if `implementation` is used then url_launcher-release.aar isn't created

**Comment by askarsyzdykov** [comment]
Btw, what does 'configuration: "default"' mean?

**Comment by askarsyzdykov** [comment]
@kezong could you say how build jar for your plugin properly? I want to test in local environment

**Comment by kezong** [comment]
@askarsyzdykov you can make local plugin by use `buildSrc` dir, see: https://docs.gradle.org/current/userguide/organizing_gradle_projects.html

**Comment by aasitnikov** [comment]
You can embed debug versions of aar using approach described in #145
