### ISSUE TITLE
 Cause: duplicate entry: META-INF/MANIFEST.MF

### ISSUE THREAD

**Issue by fza3230200** [kezong/fat-aar-android#89]
classpath 'com.android.tools.build:gradle:3.6.0-beta01'
  distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.1-all.zip
 
这个gradle 打出来的aar包  引入工程中,编译总是会报错 Cause: duplicate entry: META-INF/MANIFEST.MF   ,请问怎么办

**Comment by kezong** [comment]
插件是没有额外处理META-INF相关文件的。
参考一下：https://stackoverflow.com/questions/47063526/duplicate-entry-meta-inf-when-build-apk-with-gradle-plugin-3-0-0-exclude-no

看看是否能解决您的问题。
