### ISSUE TITLE
Not working with Gradle plugin 3.4

### ISSUE THREAD

**Issue by bachhoan88** [kezong/fat-aar-android#9]
No signature of method: org.gradle.api.internal.artifacts.DefaultResolvedArtifact.getBuildDependencies() is applicable for argument types: () values: []

**Comment by kezong** [comment]
Sorry, there is no adaptation for gradle plugin 3.4 at this time.

**Comment by kezong** [comment]
@bachhoan88 I have adapted gradle plugin version 3.4 in version 1.1.6. You can try it.
