### ISSUE TITLE
R文件找不到，请问怎么解决啊

### ISSUE THREAD

**Issue by hf529270451** [kezong/fat-aar-android#91]
打包以后提示R文件找不到符合和变量

''
/Users/hfyd/AndroidStudioProjects/fleet/fleet/application/build/intermediates/exploded-aar/r/cn/bertsir/zbar/R.java:597: 错误: 找不到符号
    public static int abc_tint_switch_thumb = com.czb.fleet.application.R.color.abc_tint_switch_thumb;
                                                                               ^
  符号:   变量 abc_tint_switch_thumb
  位置: 类 color
/Users/hfyd/AndroidStudioProjects/fleet/fleet/application/build/intermediates/exploded-aar/r/cn/bertsir/zbar/R.java:635: 错误: 找不到符号
    public static int design_textinput_error_color_dark = com.czb.fleet.application.R.color.design_textinput_error_color_dark;
                                                                                           ^
  符号:   变量 design_textinput_error_color_dark
  位置: 类 color
/Users/hfyd/AndroidStudioProjects/fleet/fleet/application/build/intermediates/exploded-aar/r/cn/bertsir/zbar/R.java:636: 错误: 找不到符号
    public static int design_textinput_error_color_light = com.czb.fleet.application.R.color.design_textinput_error_color_light;
                                                                                            ^
  符号:   变量 design_textinput_error_color_light
  位置: 类 color
/Users/hfyd/AndroidStudioProjects/fleet/fleet/application/build/intermediates/exploded-aar/r/cn/bertsir/zbar/R.java:927: 错误: 找不到符号
    public static int avd_hide_password_1 = com.czb.fleet.application.R.drawable.avd_hide_password_1;
                                                                                ^
  符号:   变量 avd_hide_password_1
  位置: 类 drawable
''

依赖是这样的：
configurations.embed.transitive = true

dependencies {
    if (runAsApp) {
        api project(':app')
    } else {
        embed project(path: ':app', configuration:'default')

        embed project(path: ':base', configuration:'default')
        embed project(path: ':lib', configuration:'default')
        embed project(path: ':uiblock_gas_list', configuration:'default')
        embed project(path: ':uiblock_gas_filter', configuration:'default')
        embed project(path: ':mode_user', configuration:'default')
        embed project(path: ':mode_share', configuration:'default')
        embed project(path: ':mode_gas_search', configuration:'default')

        embed project(path: ':picker', configuration:'default')
        embed project(path: ':wheelview', configuration:'default')

        //embed 'com.youth.banner:banner:1.4.10'
        embed 'com.gyf.immersionbar:immersionbar:3.0.0-beta07'
        embed 'com.gyf.immersionbar:immersionbar-components:3.0.0-beta07'

        embed 'com.czb.chezhubang.android.base.lib:core:0.0.5-SNAPSHOT'
    }
}

**Comment by JasonWu1111** [comment]
遇到相同的问题 +1

**Comment by waryard** [comment]
你把R前边的包名删了再试试
