### ISSUE TITLE
setProperty archivesBaseName 导致找不到 aar

### ISSUE THREAD

**Issue by shily** [kezong/fat-aar-android#92]
```gradle
defaultConfig {
    setProperty('archivesBaseName', "mylib-${versionName}_${versionCode}") 
}
```

日志:
```
> Task :mylib:reBundleAarDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mylib:reBundleAarDebug'.
> Cannot expand ZIP '/Users/work/mylib-android/mylib/build/outputs/aar/mylib.aar' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

同时，无法处理 release 和 debug 同时出包，执行 `./gradlew :mylib:assemble` 后，仅仅生成一个包，而不是 mylib-release 和 mylib-debug 两个包

**Comment by kezong** [comment]
感谢反馈
麻烦提供一下gradle和gradle plugin的版本。

**Comment by shily** [comment]
>classpath 'com.android.tools.build:gradle:3.1.4'
>classpath 'com.kezong:fat-aar:1.2.7'
>
>distributionUrl=gradle-5.1.1-all.zip

更新到 gradle:3.2.0/gradle:3.3.0 可以编译通过，
但命令 `./gradlew :mylib:assemble` 后，目标目录仅仅有一个 aar，而不是期望的 debug 一个，release 一个。

更新到 gradle:3.4.0 可以编译通过，命令 `./gradlew :mylib:assemble` 后，结果正常，生成两个 aar。

**Comment by kezong** [comment]
gradle和gradle plugin版本间的适配并没有做得很完美，建议使用最新版本吧。
