### ISSUE TITLE
生成的aar包中没有项目中的assets中的资源

### ISSUE THREAD

**Issue by zql910505** [kezong/fat-aar-android#95]
一个modle项目中打包aar文件  最后生成的aar文件中没有找到关于图片和文件的资源文件，请问应该怎么操作才会有

classpath 'com.android.tools.build:gradle:3.5.0'
gradle-5.6.2-all.zip

**Comment by kezong** [comment]
你的资源文件是放在module中的assets文件夹内，还是jar包内？

**Comment by zql910505** [comment]
资源文件module中的assets
![image](https://user-images.githubusercontent.com/16352550/68741827-9d421180-0629-11ea-9938-ce76b647dbb0.png)

项目的module中也依赖一个 基础的moduleB，moduleB也有资源 。最后aar中没有包含任何一个资源的

**Comment by zql910505** [comment]
资源文件module中的assets
项目的module中也依赖一个 基础的moduleB，moduleB也有资源 。最后aar中没有包含任何一个资源的
![image](https://user-images.githubusercontent.com/16352550/68742005-0f1a5b00-062a-11ea-8f3b-7000c3b58912.png)

**Comment by kezong** [comment]
看你截图中的目录，assets没有在默认路径下，看看是否有在build.gradle中sourceSets上加入该资源目录？
```gradle
android {
    sourceSets {
        main {
            assets.srcDirs = ['assets']
        }
}
```

**Comment by zql910505** [comment]
试了下加上之后还是有同样的问题，和没加打出来的包是一样的

**Comment by kezong** [comment]
是在有assets的module中的build.gradle加的吗？
把assets放在module默认的assets目录下的src/main/assets试试。

**Comment by zql910505** [comment]
不好意思 之前的路径写错了 所以aar中 没有资源 ，找到对应的路径就可以了
sourceSets {
        main {
            assets.srcDirs = ['../../assets']
        }
    }

**Comment by zql910505** [comment]
不过原生项目引入aar的时候找不到 io.flutter.app.FlutterActivity; 和 io.flutter.plugin.common.BasicMessageChannel;  类似这样的类 。

**Comment by zql910505** [comment]
aar包里边有资源但是不能被引用 应该还是有什么小的问题在里边

**Comment by zql910505** [comment]
谢谢指导，已经找到方法了，感谢

**Comment by xuzhongpeng** [comment]
> 谢谢指导，已经找到方法了，感谢

请问是如何解决的呢  你这个是对flutter打包吗
